
Below are relevant files from two R packages related to my repbox project

# Package repboxDRF


# FILE: /home/rstudio/repbox/repboxDRF/DESCRIPTION
```
Package: repboxDRF
Type: Package
Title: Repbox Direct Replication Format
Version: 0.1.0
Authors@R: c(
    person(
      "Sebastian", "Kranz",
      email = "sebastian.kranz@uni-ulm.de",
      role = c("aut", "cre")
    )
  )
Description: Tools to transform a Stata reproduction package into a format that facilitates direct
  replications of regressions in Stata or R. Key idea is to identify data modification steps,
  determine which can be translated to R. 
License: GPL >= 2.0
Encoding: UTF-8
LazyData: true
Depends: repboxUtils, repboxDB, stata2r
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/DESCRIPTION

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/cmd_types.R
```
# Helper function to make vector function

helper_make_drf_stata_cmd_types_vec = function() {
  cmd_types = drf_stata_cmd_types()
  types = names(cmd_types)
  res = unlist(lapply(types, function(type) {
    if (type=="need_cache") return(NULL)
    cmds = cmd_types[[type]]
    if (type=="possible_mod") type="mod"
    res = rep(type, length(cmds))
    names(res) = cmds
    res
  }))
  cat(paste0(names(res),'="', res,'"', collapse=", "))


}


drf_stata_cmd_types = function() {
  #
  # IMPORTANT: IF YOU ADD A COMMAND HERE
  # ALSO ADD IT IN stata.data.cmd.types.vec
  # Otherwise strange errors occur
  #
  list(
    load = c("u","us", "use","insheet","infix","import","sysuse","guse","gzuse"),
    preserve = c("preserve"),
    restore = c("restore"),
    # Commands that modify data and can be translated to R
    mod = c("g","ge","gen","generate","replace","drop","keep","rename","merge","egen","xtset","tsset", "xtile","pctile","append","tabulate","tabul","tabu", "tab","ta","encode","predict","xi", "collapse", "sort","so","tab1", "winsor"),
    scalar = c("scalar"),
    # Commands that modify data but cannot be translated to R
    # predict also needs cache because it may use
    # results from previous regression
    need_cache = c("merge","xtile","pctile","append","tabulate","tabul","tabu", "tab","ta","encode","predict","xi","collapse","sort","so","tab1", "winsor"),

    # Commands that under certain conditions modify the data
    # tabulate creates vpidiables if called with the gen option
    possible_mod = c("tabulate","tabul","tabu", "tab","ta","tab1"),
    xtset = c("xtset","tsset"),
    reg = repboxStata::stata_cmds_reg(),
    quasi_reg = repboxStata::stata_cmds_quasireg(),
    post_reg = repboxStata::stata_cmds_postreg()

  )
}

drf_stata_cmd_types_vec = function() {
  return(c(
u="load", us="load", use="load", insheet="load", infix="load", import="load", sysuse="load", guse="load", gzuse="load", preserve="preserve", restore="restore", g="mod", ge="mod", gen="mod", generate="mod", replace="mod", drop="mod", keep="mod", rename="mod", merge="mod", egen="mod", xtset="mod", tsset="mod", xtile="mod", pctile="mod", append="mod", tabulate="mod", tabul="mod", tabu="mod", tab="mod", ta="mod", encode="mod", predict="mod", xi="mod", collapse="mod", sort="mod", so="mod", tab1="mod", winsor="mod", tabulate="mod", tabul="mod", tabu="mod", tab="mod", ta="mod", tab1="mod", reg="reg", areg="reg", ivregress="reg", ivreg="reg", ivreg2="reg", sureg="reg", reghdfe="reg", reg2hdfe="reg", xtreg="reg", xtivreg2="reg", xtlogit="reg", xtprobit="reg", xttobit="reg", regress="reg", cgmreg="reg", intreg="reg", boxcox="reg", qreg="reg", truncreg="reg", cnsreg="reg", eivreg="reg", nl="reg", rreg="reg", bsqreg="reg", sqreg="reg", iqreg="reg", vwls="reg", sem="reg", gsem="reg", glm="reg", cloglog="reg", logit="reg", logistic="reg", blogit="reg", glogit="reg", binreg="reg", scobit="reg", probit="reg", dprobit="reg", ivprobit="reg", bprobit="reg", gprobit="reg", hetprobit="reg", heckprobit="reg", biprobit="reg", tobit="reg", ivtobit="reg", clogit="reg", obprobit="reg", ologit="reg", heckoprobit="reg", rologit="reg", asroprobit="reg", slogit="reg", mlogit="reg", asclogit="reg", nlogit="reg", asmprobit="reg", mprobit="reg", poisson="reg", ivpoisson="reg", nbreg="reg", gnbreg="reg", tpoisson="reg", tnbreg="reg", zip="reg", zinb="reg", exlogistic="reg", expoisson="reg", arch="reg", frontier="reg", reg3="reg", heckman="reg", etregress="reg", etpoisson="reg", arima="reg", arfima="reg", newey="reg", var="reg", svar="reg", vec="reg", dfactor="reg", ppmlhdfe="reg", svyreg="reg", ppml="reg", rd="quasi_reg", rdrobust="quasi_reg", psmatch2="quasi_reg", leebounds="quasi_reg", a2reg="quasi_reg", xtabond2="quasi_reg", altrdrobust="quasi_reg", hausman="quasi_reg", stcox="quasi_reg", xtivreg="quasi_reg", ivreghdfe="quasi_reg", condivreg="quasi_reg", oprobit="quasi_reg", xtpoisson="quasi_reg", newey2="quasi_reg", hetprob="quasi_reg", reg2hdfespatial="quasi_reg", outreg2="post_reg", estadd="post_reg", estimates="post_reg", predict="post_reg", test="post_reg", matrix="post_reg", est="post_reg", outreg="post_reg", eststo="post_reg", testparm="post_reg", lincom="post_reg", esttab="post_reg", margins="post_reg", estout="post_reg", estat="post_reg", nlcom="post_reg", plotcoeffs="post_reg", mfx="post_reg", boottest="post_reg", regsave="post_reg", center_estimates="post_reg", estimate="post_reg", est2vec="post_reg", suest="post_reg", fitstat="post_reg", parmest="post_reg", post="post_reg", estpost="post_reg", savereg="post_reg", wild="post_reg", rivtest="post_reg", sigstar2="post_reg", modl="post_reg", svmat="post_reg", sig_p="post_reg", ttest="post_reg", lincomestadd="post_reg", coefplot="post_reg", eret2="post_reg", get_coef="post_reg", cgmwildboot="post_reg", vareffects="post_reg", bootwildct="post_reg", post_param="post_reg", avplot="post_reg", addtotable="post_reg", margin="post_reg", vce2way="post_reg", save_results="post_reg", ivstack="post_reg", predictnl="post_reg", spatdiag="post_reg", parmby="post_reg", testnl="post_reg", b_xt="post_reg", V_xt="post_reg", p_vals="post_reg", inteff="post_reg", est2tex="post_reg", meff="post_reg", marginsplot="post_reg", iv_stack="post_reg", dfuller="post_reg", ivhettest="post_reg", pValueFormatting="post_reg", estwrite="post_reg", dfbeta="post_reg", margeff="post_reg", modltbl="post_reg", outsheet="post_reg", outtex="post_reg", lincomest="post_reg", mfx2="post_reg", addstars="post_reg", scalar="scalar", xtset="xtset",tsset="xtset"
    ))
}



pide_possible_mod_cmd_real_mod = function(run.df) {
  restore.point("pide_possible_mod_cmd_real_mod_cmd")
  is.mod = rep(TRUE, NROW(run.df))

  tab.rows = which(run.df$cmd %in% c("tabulate","tabul","tabu", "tab","ta"))
  if (length(tab.rows)>0) {
    opts = str.right.of(run.df$cmdline[tab.rows],",")
    opts = trimws_pidound(opts,"\\(")
    rx = paste0("(", c("gen","gene","gener","generate"),"\\()", collapse="|")
    is.gen = grepl(rx, opts)
    is.mod[tab.rows] = is.gen
  }
  is.mod
}




```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/cmd_types.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_cache.R
```
drf_cache_info = function() {
  cache = getOption("repboxDRF.mcache")
  if (is.null(cache)) {
    cat("\nNo drf_cache stored.\n")
    return(invisible())
  }
  cat("\nCache for ", cache$project_dir)

  cat("\ndata_for_runid:\n")
  print(names(cache$data_for_runid))

  cat("\ndata_for_file:\n")
  print(names(cache$data_for_file))

  cat("\nfile_mcache_cand:\n")
  cat(paste0(cache$file_mcache_cand$file, collapse=", "))
  cat("\n")

  cat("\nrunid_mcache_cand:\n runids:")
  cat(paste0(cache$runid_mcache_cand$runid, collapse=", "))
  cat("\n")

  invisible()
}

drf_cache_object = function(project_dir) {
  getOption("repboxDRF.mcache")
}

drf_has_cache = function(runid=NULL,file=NULL, project_dir = NULL) {
  drf_has_mcache(runid,file, project_dir)
}

drf_cached_data = function(runid=NULL, file=NULL, project_dir = NULL) {
  drf_get_mcache_data(runid,file, project_dir)
}


drf_init_mcache = function(project_dir,file_mcache_cand = NULL, runid_mcache_cand=NULL,  clear=FALSE) {
  restore.point("drf_init_mcache")
  cache = getOption("repboxDRF.mcache")

  if (!clear & isTRUE(cache$project_dir == project_dir)) return(cache)
  cache = new.env(parent=emptyenv())

  cache$project_dir = project_dir
  cache$data_for_runid = new.env(hash=TRUE, parent=emptyenv())
  cache$data_for_file = new.env(hash=TRUE, parent=emptyenv())
  cache$file_mcache_cand = file_mcache_cand
  cache$runid_mcache_cand = runid_mcache_cand
  options(repboxDRF.mcache = cache)
  invisible(cache)
}


drf_set_file_mcache_cand = function(cache_cand,project_dir=NULL, field="file_mcache_cand") {
  restore.point("drf_set_file_mcache_cand")
  cache = getOption("repboxDRF.mcache")
  new_cache = FALSE
  if (is.null(cache))  {
    new_cache = TRUE
  } else if (!is.null(project_dir)) {
    if (!isTRUE(cache$project_dir == project_dir))
      new_cache = TRUE
  }
  if (new_cache) {
    cache = drf_init_mcache(project_dir=project_dir)
  }
  cache[[field]] = cache_cand
  invisible(cache)
}

drf_set_runid_mcache_cand = function(cache_cand,project_dir=NULL, field="runid_mcache_cand") {
  drf_set_file_mcache_cand(cache_cand,project_dir, field)
}


drf_store_if_mcache_cand = function(data, runid=NULL, file=NULL, project_dir=NULL, overwrite=FALSE) {
  restore.point("drf_save_if_mcache_cand")
  if (!overwrite) {
    if (drf_has_mcache(runid, file, project_dir)) return(FALSE)
  }
  cache = getOption("repboxDRF.mcache")
  if (!is.null(runid)) {
    do_store = runid %in% cache$runid_mcache_cand$runid
  } else if (!is.null(file)) {
    do_store = file %in% cache$file_mcache_cand$file
  }
  if (!do_store) return(FALSE)
  drf_store_mcache(data, runid=runid, file=file, project_dir=project_dir)
}


drf_has_mcache = function(runid=NULL, file=NULL, project_dir = NULL) {
  cache = getOption("repboxDRF.mcache")
  if (is.null(cache)) return(FALSE)
  if (!is.null(project_dir)) {
    if (!isTRUE(cache$project_dir == project_dir))
      return(FALSE)
  }
  if (!is.null(runid)) {
    exists(paste0("r", runid), cache$data_for_runid)
  } else if (!is.null(file)) {
    exists(paste0(file), cache$data_for_file)
  } else {
    stop("provide runid or file")
  }
}


drf_get_mcache_data = function(runid=NULL,file=NULL, project_dir = NULL) {

  cache = getOption("repboxDRF.mcache")
  if (is.null(cache)) return(NULL)
  if (!is.null(project_dir)) {
    if (!isTRUE(cache$project_dir == project_dir)) return(NULL)
  }
  if (!is.null(runid)) {
    get(paste0("r", runid), envir=cache$data_for_runid)
  } else if (!is.null(file)) {
    cache$data_for_file[[file]]
  } else {
    stop("provide runid or file")
  }
}

drf_store_mcache = function(data, runid=NULL, file=NULL, project_dir=NULL) {
  cache = drf_init_mcache(project_dir, clear=FALSE)
  if (!is.null(runid)) {
    cache$data_for_runid[[paste0("r", runid)]] = data
  } else if (!is.null(file)) {
    cache$data_for_file[[file]] = data
  } else {
    stop("provide runid or file")
  }
  invisible(cache)
}

drf_find_file_mcache_cand = function(path_df=drf$path_df, run_df = drf$run_df, drf=NULL) {
  restore.point("drf_find_file_mcache_cand")
  names(path_df)
  drf_require(has_col(path_df, "found_path"), "path_df has not column 'found_path' make sure drf_add_path_df_cols_for_cache was called.", drf)

  runids = unique(path_df$runid)
  path_df %>%
    filter(runid %in% runids, found_path != "") %>%
    group_by(found_path) %>%
    summarize(num_pid = n_distinct(pid)) %>%
    unique() %>%
    rename(file=found_path)
}


# Maximum cache:
# whenever the result of a runid can be used twice and is not dominated
# cache the result
#
# The result of a runid can be used twice if at least two pid use the same runid
# It is not dominated if there is no other larger runid that uses exactly the
# same pid. We then rather want to cache the result from the larger runid
# Not that execution sequence will never violate the order of runids
drf_find_runid_mcache_cand = function(path_df=drf$path_df,ignore_load=TRUE, drf=NULL) {
  restore.point("drf_find_max_cache_runids")

  df = path_df %>%
    # only use runid that
    filter(is_load_mod)
  if (ignore_load) {
    df = df %>% filter(cmd_type != "load")
  }

  df %>%
    group_by(runid) %>%
    summarize(
      num_pid = n(),
      pid_str = paste0(sort(pid), collapse=",")
    ) %>%
    # there at least two pathes with the same runid
    filter(num_pid >= 2) %>%
    # get for every unique path combination
    # the largest runid
    group_by(pid_str) %>%
    filter(runid == max(runid))
}



drf_path_df_to_split_df = function(path_df) {
  split_df  = path_df %>%
    group_by(runid) %>%
    mutate(
      earliest_pid = min(pid)
    ) %>%
    group_by(pid, earliest_pid) %>%
    slice(n())
}


```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_cache.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_create.R
```
# Creates a new DRF
# can be run after a reproduction run

example = function() {
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_create(project_dir, overwrite=TRUE)

}

has_drf = function(project_dir) {
  file.exists(file.path(project_dir,"drf/path_df.fst"))
}

drf_create = function(project_dir, parcels=list(), acmds = drf_acmds(), overwrite=FALSE, move_from_mod=TRUE) {
  restore.point("drf_create")

  if (!overwrite & has_drf(project_dir)) {
    return(NULL)
  }
  project_dir = normalizePath(project_dir)

  drf = list(project_dir = project_dir, drf_dir = file.path(project_dir, "drf"), parcels = parcels, acmds=acmds)
  drf$parcels = repboxDB::repdb_load_parcels(project_dir, "stata_run_cmd", parcels=parcels)


  run_df = drf_make_run_df(drf=drf,add_rcode = FALSE)
  if (is.null(run_df)) {
    cat(("\nNo stata_run_cmd parcel exists, cannot create drf.\n"))
    return(NULL)
  }

  drf$run_df = run_df

  drf$pid = drf_find_pid(drf$run_df, drf$acmds)

  drf$path_df = drf_make_paths(drf)
  drf$index_df = drf_save_path_df(drf=drf)
  drf$runids = drf_runids(drf)

  drf_copy_org_data(drf=drf, move_from_mod=move_from_mod)

  drf = drf_make_r_trans_parcel(drf)
  invisible(drf)
}

# gets run_df from parcels including up-to-date cmd_type column
repbox_get_run_df = function(project_dir, parcels=list()) {
  parcels = repboxDB::repdb_load_parcels(project_dir, "stata_run_cmd", parcels=parcels)
  run_df = parcels$stata_run_cmd
  cmd_types = drf_stata_cmd_types_vec()
  run_df$cmd_type = cmd_types[run_df$cmd]
  run_df
}

# Analysis commands
drf_acmds = function() {
  # Don't use post regression commands for normal paths
  unique(c(repboxStata::stata_cmds_reg(), repboxStata::stata_cmds_quasireg()))
  #unique(c(repboxStata::stata_cmds_reg(), repboxStata::stata_cmds_postreg_comp(), repboxStata::stata_cmds_quasireg()))

}



drf_find_pid = function(run_df,acmds = drf_acmds()) {
  restore.point("drf_find_pid")
  run_df$runid[(run_df$cmd %in% acmds) & run_df$ok]
}

require_project_dir = function(project_dir) {
  if (is.null(project_dir)) stop("You must supply a valid project_dir")
  if (!dir.exists(project_dir)) stop("You must supply an existing project_dir")
}


require_drf_dir = function(drf_dir) {
  if (is.null(drf_dir)) stop("You must supply a valid drf_dir")
  project_dir = dirname(drf_dir)
  if (dir.exists(project_dir)) stop("You must supply a valid drf_dir for an existing project_dir.")

}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_create.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_filter_code.R
```
# Code to filter the data set according to an if or in condition
# in a regression command

# At some point we may want to generalize it to non regression commands

# FILE: repboxDRF/R/drf_filter_code.R

drf_get_filter_code = function(runid, drf, parcels=drf$parcels) {
  restore.point("drf_get_filter_code")

  parcels = repboxDB::repdb_load_parcels(drf$project_dir, "reg_cmdpart", parcels=drf$parcels)
  cmdpart = parcels$reg_cmdpart

  cp = cmdpart[cmdpart$runid == runid, ]
  if (NROW(cp) == 0) {
    cat("\nNot any existing cmdpart stored for runid=", runid, ". Cannot get if and in conditions.")
    return(character(0))
  }
  if_str = cp$content[cp$part == "if_str"]
  in_str = cp$content[cp$part == "in_str"]

  filter_code = character(0)

  if (length(if_str) > 0 && nzchar(if_str[1])) {
    # Get the context to accurately translate the if expression natively via stata2r
    path_df = drf$path_df
    pid = first(path_df$pid[path_df$runid == runid])
    if (is.na(pid)) pid = runid

    path_df_full = path_df[path_df$pid == pid & path_df$runid <= runid,]
    stata_code = drf$run_df$cmdline[match(path_df_full$runid, drf$run_df$runid)]

    # Protect newlines to avoid row index shifting
    stata_code = gsub("\n", " ", stata_code, fixed = TRUE)

    cmd_df = stata2r::do_parse(stata_code)
    cmd_df = stata2r::mark_data_manip_cmd(cmd_df)

    line_num = NROW(cmd_df)

    # STRIP 'if' KEYWORD
    # The 'if_str' from cmdpart includes the 'if' keyword, e.g. "if u_sample == 1".
    # Strip it before passing to translation.
    if_expr = sub("^\\s*if\\s+", "", if_str[1], ignore.case = TRUE)

    r_if_cond = stata2r::translate_stata_expression_with_r_values(
      if_expr, line_num, cmd_df, list(is_by_group = FALSE)
    )

    if (!is.na(r_if_cond)) {
      r_if_cond_quoted = encodeString(r_if_cond, quote = '"')
      filter_code = c(filter_code, paste0("data = stata2r::scmd_keep(data, r_if_cond = ", r_if_cond_quoted, ")"))
    } else {
      repboxUtils::repbox_problem(
        msg = paste0("Failed to translate if condition for runid ", runid),
        type = "filter_translation_error",
        project_dir = drf$project_dir,
        fail_action = "warn"
      )
    }
  }

  if (length(in_str) > 0 && nzchar(in_str[1])) {
    # STRIP 'in' KEYWORD
    # The 'in_str' includes 'in', e.g. "in 1/100". Strip it!
    in_expr = sub("^\\s*in\\s+", "", in_str[1], ignore.case = TRUE)

    r_in_range = stata2r::s2r_in_str_to_r_range_str(in_expr)
    if (!is.na(r_in_range)) {
      r_in_range_quoted = encodeString(r_in_range, quote = '"')
      in_code = paste0("data = stata2r::scmd_keep(data, r_in_range = ", r_in_range_quoted, ")")
      filter_code = c(filter_code, in_code)
    }
  }

  return(filter_code)
}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_filter_code.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_paths.R
```
# part of DAP function
#
# Here we make the first part: extraction of data paths
# Notation is a bit old and not the same as in dap.R
#
# step: refers to a row in run_df
# node: refers to an analysis step (astep)


drf_make_paths = function(drf) {
  restore.point("drf_make_paths")
  run_df = drf$run_df; project_dir = drf$project_dir
  pid = drf$pid
  if (is.null(drf$pid)) {
    stop("Please specify drf$pid, the analyis runid of run_df.")
  }

  type_vec = drf_stata_cmd_types_vec()

  run_df = run_df %>%
    mutate(
      cmd_type = type_vec[cmd]
    )

  # Split run_df by root_file_path and compute path_df
  # Then merge path_df again for all run_df
  srun_li = split(run_df,run_df$root_file_path)
  path_li = lapply(srun_li, find_one_root_data_paths, pid=pid)
  path_df = bind_rows(path_li)

  if (NROW(path_df)==0) {
    cat("\nNo regression command found.")
    return(NULL)
  }
  return(path_df)
}


find_one_root_data_paths = function(srun_df, pid) {
  restore.point("find_one_root_data_paths")

  srun_df$.ROW = seq_len(NROW(srun_df))
  srun_df = add_load_blocks_to_run_df(srun_df)

  spid_rows = match(pid, srun_df$runid)
  spid_rows = spid_rows[!is.na(spid_rows)]

  path_df = bind_rows(lapply(spid_rows, find_data_run_path, srun_df = srun_df, pid=pid))

  if (NROW(path_df)==0) return(NULL)
  path_df
}


extract_run_tree_from_path_df = function(root, path_df) {
  restore.point("extract_tree_from_path_df")
  tree_df = path_df %>%
    group_by(node) %>%
    mutate(
      step_ind = 1:n(),
      root_ind = match(root, dstep),
      del = is.na(root_ind) | step_ind < root_ind
    ) %>%
    ungroup() %>%
    filter(!del) %>%
    select(-step_ind, root_ind, del)
}



# FILE: repboxDRF/R/drf_paths.R
# Replace the existing find_data_run_path function:

find_data_run_path = function(pid_row, srun_df, pid=NULL) {
  restore.point("find_data_run_path")

  # All runid in same load block until pid
  path = which(srun_df$load_block == srun_df$load_block[pid_row] & srun_df$.ROW <= pid_row)

  # If we start with a restore command then jump to previous preserve
  # and then add all rows with the same load_block
  while (TRUE) {
    if (srun_df$cmd[path[1]] == "restore") {
      pr_row = srun_df$preserve_row[path[1]]
      new_path = which(srun_df$load_block == srun_df$load_block[pr_row] & srun_df$.ROW < pr_row)
      path = c(new_path, path[-1])
      next
    }
    break
  }

  # Adapt path: Use stata2r to accurately determine which commands have data
  # manipulation side effects or are relied upon by later commands.
  stata_code = srun_df$cmdline[path]
  stata_code = gsub("\n", " ", stata_code, fixed = TRUE)
  cmd_df = stata2r::s2r_check_mod(stata_code)

  cmd_types = drf_stata_cmd_types()
  allow = c(cmd_types$scalar, cmd_types$xtset)

  keep = seq_along(path) %in% c(1, length(path)) |
    cmd_df$is_mod |
    srun_df$cmd[path] %in% allow |
    srun_df$runid[path] %in% pid

  path = path[keep]

  return( tibble(pid=srun_df$runid[pid_row], runid=srun_df$runid[path]))
}


# Only works for run_df that have a single rootdonum
add_load_blocks_to_run_df = function(run_df) {
  restore.point("add_load_blocks_to_run_df")
  cmd_types = drf_stata_cmd_types()
  load_cmds = cmd_types$load

  run_df$load_block = cumsum(run_df$cmd %in% c(load_cmds,"restore"))

  # Deal with preserve / restore
  run_df$preserve_row = NA
  pr_rows = which(run_df$cmd %in% c(cmd_types$preserve, cmd_types$restore))
  cur_preserve = NA
  for (r in pr_rows) {
    if (run_df$cmd[r]== "preserve") {
      cur_preserve = r
    } else if (!is.na(cur_preserve)) {
      run_df$preserve_row[r] = cur_preserve
      #rows = which(run_df$load_block == run_df$load_block[r])
      #run_df$load_block[rows] = run_df$load_block[cur_preserve]
    } else {
      wpidning("Restore command without previous preserve command is encountered!")
    }
  }
  run_df
}

#
# plot_path_df = function(path_df) {
#
#   blues_col = c("#EFF3FF", "#BDD7E7", "#6BAED6", "#3182BD", "#08519C")
#   reds_col = c("#FFFFB2", "#FECC5C", "#FD8D3C", "#F03B20", "#BD0026")
#   greens_col = c("#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45")
#
#   if (!"cache" %in% colnames(path_df)) {
#     path_df$cache = FALSE
#   }
#
#   pid = path_df %>%
#     group_by(dstep) %>%
#     summarize(
#       cache = first(cache),
#       time = first(time),
#       step_type = first(step_type),
#       time = first(time),
#       time_int = 1 + (time>1) + (time > 10) + (time > 100) + (time > 1000),
#       steplab = first(steplab)
#     ) %>%
#     mutate(
#       id = 1:n(),
#       shape = ifelse(step_type=="load","dot","box"),
#       color = case_when(
#         #step_type == "load" ~ blues_col[time_int],
#         cache ~ blues_col[time_int],
#         step_type == "node" ~ greens_col[time_int],
#         TRUE ~ reds_col[time_int]
#       ),
#       label = paste0(shorten.str(steplab,30),"\n",signif(time,2)," sec."),
#       title = paste0(shorten.str(gsub("\n","<br>",steplab, fixed=TRUE),100),"<br>",signif(time,3)," sec.","<br>dstep = ",dstep)
#     )
#
#   edges = path_df %>%
#     left_join(select(pid, dstep, id), by="dstep") %>%
#     group_by(node) %>%
#     transmute(
#       from = id,
#       to = lead(id)
#     ) %>%
#     ungroup() %>%
#     filter(!is.na(to)) %>%
#     select(from, to) %>%
#     distinct() %>%
#     mutate(pidrows = "to")
#
#   title = paste0("Data-Regression Network")
#   librpidy(visNetwork)
#   vis = visNetwork(pid, edges,
#                    main = list(text=title,style="font-family: Helvetia, sans-serif;font-weight:bold;font-size:20px; text-align: center;")
#   )
#   vis
#
#
# }
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_paths.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf.R
```
example = function() {
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_load(project_dir)

}


# To do: variant that is faster for selected paths
drf_load = function(project_dir, parcels=list()) {
  restore.point("drf_load")
  project_dir = normalizePath(project_dir)
  drf = list(project_dir = project_dir, drf_dir = file.path(project_dir, "drf"), parcels = parcels)
  drf$parcels = repboxDB::repdb_load_parcels(project_dir, c("stata_run_cmd", "r_trans"), parcels=parcels)
  drf$run_df = drf_make_run_df(drf=drf,add_rcode = TRUE)
  drf$path_df = drf_load_path_df(drf=drf)
  drf$path_df = drf_add_path_df_cols_for_cache(drf=drf)
  drf$runids = drf_runids(drf)
  drf$pids= drf_pids(drf)
  drf
}

drf_pids = function(drf, path_df=drf$path_df) {
  if (!is.null(drf[["runids"]])) drf$pids
  unique(drf$path_df$pid)
}

drf_runids = function(drf, path_df=drf$path_df) {
  if (!is.null(drf[["runids"]])) drf$runids
  unique(drf$path_df$runid)
}


drf_make_run_df = function(project_dir = drf$project_dir, parcels=drf$parcels, drf = list(parcels=list()), add_rcode = TRUE) {
  restore.point("drf_make_run_df")
  parcels = repboxDB::repdb_load_parcels(project_dir, "stata_run_cmd", parcels=parcels)
  run_df = parcels$stata_run_cmd

  start_time = run_df$start_time[1]
  run_df$ok = !is.true(run_df$errcode != 0) & !is.true(run_df$missing_data)
  run_df$start_sec = sec_since_start(run_df$start_time, start_time)
  run_df$end_sec = sec_since_start(run_df$end_time, start_time)
  run_df$dur_sec =run_df$end_sec - run_df$start_sec

  cmd_types = drf_stata_cmd_types_vec()
  run_df$cmd_type = cmd_types[run_df$cmd]

  rows = run_df$cmd_type == "reg"
  inds = which(has.substr(run_df$cmdline[rows]," _I"))
  run_df$is_I_reg = FALSE
  run_df$is_I_reg[rows[inds]] = TRUE

  rows = run_df$cmd_type %in% c("reg","mod")
  inds = which(stri_detect_regex(run_df$cmdline[rows],"(^|[ \\:])[ ]*xi[ \\:]"))
  run_df$is_xi = FALSE
  run_df$is_xi[inds] = TRUE


  if (add_rcode) {
    parcels = repboxDB::repdb_load_parcels(project_dir, "r_trans", parcels=parcels)
    rt_df = parcels$r_trans
    if (is.null(rt_df)) {
      stop("\nNo r_trans parcel exists generate it.")
    }
    if (!is.null(rt_df)) {
      run_df = remove_cols(run_df, "rcode")
      run_df = left_join(run_df, rt_df, by="runid") %>%
        mutate(rcode = na.val(rcode, ""))
    }
  }

  run_df
}

# Needs to be refined. We do not yet know how to handle regressions
# that modify the data set.
# We probably need a special data modification translation
drf_add_path_df_cols_for_cache = function(path_df = drf$path_df, run_df=drf$run_df, drf=NULL, overwrite=FALSE) {
  restore.point("drf_mark_path_df_is_load_mod")
  if (!overwrite) {
    if (has_col(path_df, "is_load_mod")) return(path_df)
  }
  cols = setdiff(names(path_df), c("cmd_type","found_path", "is_xi", "is_I_reg","is_load_mod"))
  path_df = path_df[,cols]
  path_df %>%
    left_join(run_df %>% select(runid, cmd_type,  found_path, is_xi, is_I_reg), by="runid") %>%
    mutate(is_load_mod = cmd_type %in% c("load","mod","merge"))

}

drf_require = function(cond, msg, drf) {
  if (!isTRUE(all(cond))) {
    stop(msg)
  }
}

```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_r_code.R
```
example = function() {
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"
  project_dir = "~/repbox/projects/test"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_load(project_dir)
  drf$sc_df = drf_stata_code_df(drf, path_merge = "load_natural")
  drf$rc_df = drf_rcode_df(drf)
}


drf_make_r_trans_parcel = function(drf) {
  restore.point("drf_make_r_trans_parcel")
  run_df = drf_run_df_create_rcode(drf=drf)
  rt_df = run_df %>%
    filter(rcode != "") %>%
    select(runid, rcode)

  drf$parcels[["r_trans"]] = rt_df
  repdb_save_parcels(drf$parcels["r_trans"],file.path(drf$project_dir, "repdb"),check=TRUE)
  drf

}

# Writes stata code skeleton for direct replication of one or
# multiple regression commands
# The regression commands themselves will be palceholder of form
# {{runid-3562}}

# TO DO: omit unneccesary previous reg steps.
# They are currently always included in path since
# later regressions may need them if r() or something is used from it.



drf_run_df_create_rcode = function(run_df=drf$run_df, runids=drf_runids(drf), drf=NULL) {
  restore.point("drf_run_df_create_rcode")

  if (!has_col(run_df, "rcode")) {
    run_df$rcode = rep("", NROW(run_df))
  }
  if (!is.null(runids)) {
    rows = match(runids, run_df$runid)
  } else {
    rows = seq_len(NROW(run_df))
  }
  rows = sort(unique(rows[!is.na(rows)]))

  update_rows = rows
  # if (!overwrite) {
  #   cat("\ndrf_run_df_create_rcode with ovewrite=FALSE might be problematic with respect to row indices. Better make just a single translation.\n")
  #   update_rows = rows[run_df$rcode[rows] == ""]
  # }

  if (length(update_rows)==0) return(run_df)

  # Translate the execution trace up to the max row so `stata2r` maintains full context
  #max_row = max(update_rows)
  stata_code = run_df$cmdline[update_rows]

  # IMPORTANT: Replace internal newlines with spaces to keep 1-to-1 mapping with rows
  stata_code = gsub("\n", " ", stata_code, fixed = TRUE)

  r_df = stata2r::do_to_r(stata_code, return_df = TRUE)

  translated_code = r_df$r_code
  run_df$rcode[update_rows] = ifelse(is.na(translated_code), "", translated_code)

  # Overwrite 'load' commands with repbox's own data loading logic
  inds = update_rows[run_df$cmd_type[update_rows] %in% c("load")]
  if (length(inds)>0) {
    code = paste0(
      'data = drf_load_data(project_dir, "', file.path(run_df$found_path[inds]) ,'")\n',
      'data$stata2r_original_order_idx = seq_len(nrow(data))\n',
      'assign("has_original_order_idx", TRUE, envir = stata2r::stata2r_env)'
    )
    run_df$rcode[inds] = code
  }
  run_df$rcode = na.val(run_df$rcode, "")

  run_df
}


drf_rcode_df = function(drf,runids=NULL, path_merge = c("none", "load", "natural", "load_natural")[4], update_rcode = FALSE) {
  restore.point("drf_rcode_df")

  # perform path merge like as for stata code
  sc_df = drf_stata_code_df(drf, runids=runids, path_merge=path_merge)
  runids = unique(rc_df$runid)

  run_df = drf$run_df
  if (update_rcode) {
    run_df = drf_run_df_create_rcode(run_df, runids=runids, overwrite=TRUE)
  }

  run_df = drf$run_df %>%
    filter(runid %in% runids)

  rc_df = rc_df %>%
    left_join(run_df %>% select(runid, cmdline,rcode), by="runid") %>%
    mutate(code = rcode, pre = "", post="")
  rc_df
}



```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_r_code.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_r_data.R
```
# Data loading and cache for R metareg analysis

# Main aspect is caching

# We can have two types of caches:
# cache in memory mcache
# cache files fcache


# For debugging purposes helpful but may destroy some
# Stata pipeline so don't add by default
drf_set_add_org_row = function(add_org_row=TRUE) {
  options(repbox_data_add_org_row=add_org_row)
  return(add_org_row)
}

drf_load_data = function(project_dir, rel_path, ..., add_org_row=isTRUE(getOption("repbox_data_add_org_row"))) {
  restore.point("repbox_load_data")
  data = drf_cached_data(file=rel_path, project_dir=project_dir)
  if (!is.null(data)) return(data)
  file = file.path(project_dir, "drf/org_data", rel_path)
  if (!file.exists(file)) {
    stop(paste0("The original data set ", rel_path, " is not yet stored in the DRF folder ", file.path(project_dir, "drf/org_data")))
  }

  ext = tolower(tools::file_ext(file))
  if (ext=="dta") {
    data = haven::read_dta(file)
  } else if (ext=="rds") {
    data = readRDS(file)
  } else {
    data = rio::import(file)
  }

  if (isTRUE(add_org_row)) {
    data = bind_cols(tibble(.ORG.ROW = seq_len(NROW(data))), data)
  }

  drf_store_if_mcache_cand(data, file=rel_path, project_dir=project_dir)

  data
}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_r_data.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_run_r.R
```
example = function() {
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"
  drf = drf_load(project_dir)
  drf$pids
  drf$path_df %>%
    group_by(pid) %>%
    summarize(ncmd = n())
  pid = 188

  # test caches
  file_mcache_cand = drf_find_file_mcache_cand(drf=drf)
  runid_mcache_cand = drf_find_runid_mcache_cand(drf=drf)
  drf_set_file_mcache_cand(file_mcache_cand, project_dir)
  drf_set_runid_mcache_cand(runid_mcache_cand, project_dir)

  class(drf_cache_object())
  names(drf_cache_object())

  drf_cache_info()

  data = drf_get_data(pid, drf=drf,update_rcode = TRUE)




}

#' The main function for metareg regressions
#' get the data set for a particular regression specified with runid

#' @param runid The runid of the command (usually regression) for which the data set shall be obtained
#' @param drf The drf object loaded with drf_load(project_dir)
#' @param filtered Shall the data set already be filtered according to the 'if' and 'in' conditions in the Stata command. Default TRUE
#' @param before Only for commands that modify data. If TRUE (default) return data set before the command modifies the data
#' @param update_rcode Set TRUE if the repbox code for R translation has been updated and the old R code is no longer up-to-date. Mostly relevant during development of the repbox package.
#' @param exec_env in which environment shall the R code that loads and modifies the data be evaluated, default a new env.
#' @param pid Alias for runid in this command (pid stands for path ID which is the runid of the final command in a path from path_df)

drf_get_data = function(runid=pid, drf, filtered=TRUE, before=TRUE, update_rcode=FALSE, exec_env = new.env(parent = globalenv()), pid=NULL) {
  restore.point("drf_get_data")
  if (is.null(runid)) {
    stop("Specify a runid (or pid as synonym).")
  }
  runids = drf_runids(drf)
  if (!runid %in% runids) {
    stop("runid is not part of any DRF path. We only build paths that lead to a successfully run regression.")
  }
  path_df = drf$path_df
  pid = first(path_df$pid[path_df$runid == runid])

  path_df_full = path_df[path_df$pid == pid,]

  if (before) {
    path_df_sub = path_df_full[path_df_full$runid < runid,]
  } else {
    path_df_sub = path_df_full[path_df_full$runid <= runid,]
  }

  exec_runids = path_df_sub$runid
  run_df = drf$run_df
  if (!has_col(run_df, "rcode") | update_rcode) {
    # Ensure full context is passed to rcode generation, including the target `pid`
    run_df = drf_run_df_create_rcode(run_df, runids=path_df_full$runid, overwrite=TRUE)
  }
  rows = match(exec_runids, run_df$runid)
  rows = rows[run_df$rcode[rows] != ""]

  rcode = run_df$rcode[rows]

  if (length(rcode)==0) {
    stop("No R code found for getting data. That looks like a bug.")
  }

  if (filtered) {
    filter_code = drf_get_filter_code(pid, drf)
    if (length(filter_code) > 0) {
      rcode = c(rcode, filter_code)
    }
  }

  # Simple execution of R code
  rcode_call = parse(text = paste0(rcode, collapse="\n"))
  exec_env$project_dir = drf$project_dir
  eval(rcode_call, envir = exec_env)

  # Crucial: Always return the manipulated data frame explicitly
  exec_env$data
}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_run_r.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_stata_code.R
```
example = function() {
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_load(project_dir)
  drf$sc_df = sc_df = drf_stata_code_df(drf, path_merge = "load_natural")


}


# Writes stata code skeleton for direct replication of one or
# multiple regression commands
# The regression commands themselves will be palceholder of form
# {{runid-3562}}

# TO DO: omit unneccesary previous reg steps.
# They are currently always included in path since
# later regressions may need them if r() or something is used from it.



drf_stata_code_df = function(drf,runids=NULL, path_merge = c("none", "load", "natural", "load_natural")[4]) {
  restore.point("drf_stata_code_skel")
  pids = runids
  path_df = drf$path_df
  if (!is.null(pids)) {
    path_df = path_df %>%
      filter(pid %in% pids)
  }
  pids = unique(path_df$pid)
  if (length(pids)<=1) path_merge = "none"

  restore_code = function(data_path) {
    # "preserve, restore"
    paste0("* Restore previously loaded data set", basename(data_path), "\nframe copy cache_frame default, replace")
  }
  preserve_code = function() {
    #"\npreserve"
    "\nframe copy default cache_frame, replace"
  }


  # Pick only those run commands that are used
  # in the selected paths
  run_df = drf$run_df
  run_df = run_df %>% semi_join(path_df, by="runid")

  # Create code for every used command line
  run_df$code = run_df$cmdline

  # Adapt data sets in load and merge commands
  run_df = drf_replace_run_df_code_data_path(run_df = run_df, drf=drf)
  run_df$data_path = run_df$org_data_path

  path_li = split(path_df, path_df$pid)
  code_li = NULL
  pid = pids[1]
  if (path_merge == "none") {
    code_li = lapply(pids, function(pid) {
      pdf = path_li[[as.character(pid)]]
      rdf = run_df[run_df$runid %in% pdf$runid, ]
      rdf %>%
        transmute(pid=pid,runid=runid, code=code, pre="", post="", cmd_type=cmd_type, cmd=cmd, is_target = runid==pid, aux_cmd_type="")
    })
    sc_df = bind_rows(code_li)
    return(sc_df)
  }
  ps_df = path_df %>%
    group_by(pid) %>%
    summarize(
      first_runid = min(runid),
      last_runid = max(runid),
    ) %>%
    left_join(run_df %>% select(first_runid=runid, data_path), by="first_runid")

  data_df = ps_df %>%
    group_by(data_path) %>%
    summarize(
      data_runid = min(first_runid),
      data_num_paths = n()
    ) %>%
    arrange(data_runid)

  ps_df = ps_df %>%
    left_join(data_df, by="data_path")

  merge_load = path_merge %in% c("load", "load_natural")
  merge_natural = path_merge %in% c("natural", "load_natural")

  if (merge_load) {
    ps_df = ps_df %>%
      ungroup() %>%
      arrange(data_runid, first_runid, last_runid) %>%
      mutate(
        restore_data = is.true(lag(data_runid)==data_runid),
        preserve_data = !restore_data & data_num_paths > 1
      )
  } else {
    ps_df = ps_df %>%
      arrange(first_runid, last_runid) %>%
      mutate(restore_data = FALSE, preserve_data=FALSE)
  }

  pids = ps_df$pid
  if (!merge_natural) {
    code_li = lapply(pids, function(pid) {
      pdf = path_li[[as.character(pid)]]
      rdf = run_df[run_df$runid %in% pdf$runid, ]
      rdf = rdf %>%
        transmute(pid=pid,runid=runid, code=code, pre="", post="", cmd_type=cmd_type, cmd=cmd, is_target = runid==pid, aux_cmd_type="", clear=FALSE)

      ps = ps_df[ps_df$pid==pid,]
      if (ps$preserve_data) {
        rdf$code[1] = paste0(rdf$code[1],preserve_code())
        rdf$aux_cmd_type[1] = paste0("load_preserve")
      } else if (ps$restore_data) {
        rdf$code[1] = restore_code(ps$data_path)
        rdf$aux_cmd_type[1] = paste0("restore")
      }
    })
    sc_df = bind_rows(code_li)
    return(sc_df)
  }

  # merge_natural==TRUE
  # means that if in the original script regressions are run consequutively
  # after each other, we will also do this in this generated script

  code_li = vector("list", length(pids))
  opdf = NULL
  counter = 0

  while (counter < length(pids)) {
    counter = counter+1
    #cat("\n", counter, "of", length(pids), pid,"\n")
    pid = pids[counter]
    pdf = path_li[[as.character(pid)]]
    if (is.null(opdf) | NROW(opdf)>=NROW(pdf)) {
      restart = TRUE
    } else {
      restart = !all(opdf$runid == pdf$runid[1:NROW(opdf)])
    }

    if (restart) {
      rdf = run_df[run_df$runid %in% pdf$runid, ]
      rdf = rdf %>%
        transmute(pid=pid,runid=runid, code=code, pre="", post="", cmd_type=cmd_type, cmd=cmd, is_target = runid==pid, aux_cmd_type="", clear=FALSE)

      ps = ps_df[ps_df$pid==pid,]

      if (ps$preserve_data) {
        rdf$code[1] = paste0(rdf$code[1],preserve_code())

        rdf$aux_cmd_type[1] = paste0("load_preserve")
      } else if (ps$restore_data) {
        rdf$code[1] = restore_code(ps$data_path)
        rdf$aux_cmd_type[1] = paste0("restore")
      }
      opdf = pdf


    } else if (!restart) {
      # continue with commands that continue previous path
      npdf = pdf %>% filter(runid > max(opdf$runid))
      opdf = pdf
      pdf = npdf

      rdf = run_df[run_df$runid %in% pdf$runid, ]
      rdf = rdf %>%
        transmute(pid=pid,runid=runid, code=code, pre="", post="", cmd_type=cmd_type, cmd=cmd, is_target = runid==pid, aux_cmd_type="", clear=FALSE)
    }
    code_li[[counter]] = rdf
  }
  sc_df = bind_rows(code_li)
  all(pids %in% sc_df$pid)
  sc_df
}

# Add to Stata code command that save data set caches as dta after some command
drf_add_code_store_cache = function(runids, sc_df=drf$sc_df,drf_dir = drf$drf_dir, drf = NULL) {
  restore.point("drf_add_code_store_cache")
  require_drf_dir(drf_dir)

  cache_dir = file.path(drf_dir, "cache_dta")
  if (!dir.exists(cache_dir)) dir.create(cache_dir)

  cache_files = file.path(cache_dir, paste0("cache_", runids, ".dta"))

  # Will only match first time runid appears in sc_df
  # but that is what we want: caching multiple times makes no sense
  rows = match(runids, sc_df$runid)

  txt = paste0(txt,'\nsave "', cache_files,'", replace\n')
  sc_df$post[rows] = paste0(txt, sc_df$post[rows])
  sc_df
}

drf_add_code_store_if_rows = function(runids, sc_df=drf$sc_df,drf_dir=drf$drf_dir, only_fun_if_rows = TRUE, drf = NULL, outdir = file.path(drf_dir, "if_rows")) {
  restore.point("drf_add_code_store_if_rows")

  rows = match(runids, sc_df$runid)
  cmdline = sc_df$cmdline[rows]

  has_if = stringi::stri_detect_regex(cmdline, "\\bif\\b")
  rows = rows[has_if]
  if (length(rows)==0) return(sc_df)
  cmdline = sc_df$cmdline[rows]

  tab = repboxStata::repbox.re.cmdlines.to.tab(cmdline)
  if_str = tab$if_arg

  # We don't want to save simple if conditions that don't call a
  # Stata function because we could translate them ourselves
  if (only_fun_if_rows) {
    use = has.substr(if_str, "(")
    rows = rows[use]
    if (length(rows)==0) return(sc_df)
    if_str = use
  }
  runids = sc_df$runid[rows]

  if (!dir.exists(outdir))
    dir.create(dir, recursive = TRUE)


  # TO CHECK restore / preserve or deletion of created row
  file = paste0(outdir, "/ifrows_", runids, ".dta")
  sc_df$pre[rows]  = paste0("\n
// Store row number from if condition
preserve
gen r0W_ox_zA___2G__nUm__ = _n
capture noisily keep if ",if_str, "
keep r0W_ox_zA___2G__nUm__
capture noisily save \"",file, "\", replace
restore\n",
    sc_df$pre[rows])
  sc_df
}


drf_code_stata_path_header = function(sc_df, header_tpl = "\n***** Path for runid={{pid}} ****\n\n", to_col="pre", append_mode = c("overwrite", "left", "right")[1]) {
  drf_code_adapt(sc_df, function(code_df, ...) {
    stringi::stri_replace_all_fixed(header_tpl,"{{pid}}", code_df$pid)
  },to_col=to_col, append_mode=append_mode, just_path_pos="start")

}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_stata_code.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_stata_data.R
```
# Functions related to data set
# already needed when generating Stata code
drf_run_df_add_data_paths = function(run_df = drf$run_df, drf_dir = drf$drf_dir, drf = NULL) {
  run_df$org_data_path = ifelse(!nzchar(run_df$found_path), NA_character_,file.path(drf_dir, "org_data", run_df$found_path))
  run_df$has_org_data = file.exists(run_df$org_data_path)

  cache_data_path = file.path(drf_dir, "cache_dta", paste0(run_df$runid,".dta"))
  has_cache_data = file.exists(cache_data_path)
  run_df$cache_data_path = ifelse(has_cache_data, cache_data_path, NA_character_)
  run_df$has_cache_data = has_cache_data
  run_df

}


drf_data_load_needs_clear = function(run_df=NULL, cmd=run_cmd$cmd, cmd_type=run_df$cmd_type) {
  cmd_type %in% c("load")
}

# This function just replaces the data path
drf_replace_run_df_code_data_path = function(run_df =drf$run_df, drf_dir = drf$drf_dir, drf = NULL, cmd_types = c("load","merge"), rows=NULL, prefer_cache = FALSE) {
  restore.point("drf_replace_run_df_org_data_path")

  if (!has_col(run_df, "org_data_path")) {
    run_df = drf_run_df_add_data_paths(run_df, drf_dir=drf_dir)
  }

  if (!has_col(run_df,"code")) {
    stop("You need the column run_df$code.")
  }

  if (is.null(rows) & !is.null(cmd_types)) {
    rows = which(run_df$cmd_type %in% cmd_types)
  } else if (is.null(rows)) {
    rows = seq_len(NROW(run_df))
  }

  if (length(rows)==0) return(run_df)


  # Replace original code that load original data set
  org_rows = rows[run_df$has_org_data[rows]]
  add_clear = drf_data_load_needs_clear(run_df[org_rows,])
  run_df$code[org_rows] = replace_stata_cmdline_path(run_df$code[org_rows], paste0('"',run_df$org_data_path[rows],'"'),add_clear=add_clear)

  # TO DO: cache replace:
  # If we load a cache, we load the cache file with a complete new load command
  # e.g. use "cachefile.dta", clear

  # ...
  run_df
}

drf_copy_org_data = function(project_dir=drf$project_dir, run_df=drf$run_df, runids=drf_runids(drf),  move_from_mod=TRUE, drf=NULL, overwrite=FALSE) {
  restore.point("drf_copy_org_data")

  require_project_dir(project_dir)
  if (!dir.exists(project_dir)) stop()

  data_files = run_df %>%
    filter(runid %in% runids, cmd_type %in% c("load","merge")) %>%
    pull(found_path) %>%
    unique()

  dest_files = file.path(project_dir,"drf/org_data", data_files)
  if (!overwrite) {
    has = file.exists(dest_files)
    dest_files = dest_files[!has]
    data_files = data_files[!has]
  }
  if (length(dest_files)==0) return(invisible(NULL))

  dirs = unique(dirname(dest_files))
  for (dir in dirs) {
    if (!dir.exists(dir))
      dir.create(dir, recursive=TRUE, showWarnings = FALSE)
  }

  # 1. Try to copy from mod folder
  mod_files = file.path(project_dir, "mod", data_files)
  has = which(file.exists(mod_files))
  if (move_from_mod) {
    file.rename(from=mod_files[has],to=dest_files[has])
  } else {
    file.copy(from=mod_files[has],to=dest_files[has], overwrite=overwrite)
  }
  if (length(has)==length(dest_files)) return()


  # 2. if not all files were in mod then copy from org
  has = file.exists(dest_files)
  dest_files = dest_files[!has]
  data_files = data_files[!has]

  org_files = file.path(project_dir, "org", data_files)
  has = which(file.exists(org_files))
  file.copy(from=mod_files[has],to=dest_files[has], overwrite=overwrite)

  has = file.exists(dest_files)
  if (!all(has)) {
    cat("\nThe data set(s) ", paste0(data_files[!has], collapse=", "), " were not found in mod or org folder and could not be copied to drf/org_data.")
  }
  return()
}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_stata_data.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/drf_tools.R
```

drf_code_adapt = function(code_df, fun, ..., to_col="code", append_mode = c("overwrite", "left", "right")[1], vectorized=FALSE, just_cmd_types=NULL,just_runids=NULL, just_path_pos = c("start","end")[2], once_per_runid=TRUE){
  restore.point("drf_adapt_code")

  rows = NULL
  if (!is.null(just_runids)) {
    runids = just_runids
  } else if (!is.null(just_cmd_types)) {
    runids = unique(code_df$runid[code_df$cmd_type %in% cmd_types])
  } else if (just_path_pos=="end") {
    rows = which(code_df$pid==code_df$runid)
    runids = code_df$runid[rows]
    once_per_runid = TRUE
  } else if (just_path_pos=="start") {
    code_df = code_df %>%
      group_by(pid) %>%
      mutate(path_pos = 1:n()) %>%
      ungroup()
    rows = which(code_df$path_pos==1)
    runids = code_df$runid[rows]
  } else if (is.null(runid)) {
    stop("Please provide just_runids, just_cmd_types or just_path_pos")
  }

  if (is.null(rows))
    rows = match(runids, code_df$runid)

  if (vectorized) {
    new_code = do.call(fun, args=list(code_df = code_df[rows,], ...))
  } else {
    new_code = sapply(rows, function(row) {
      do.call(fun, args=list(code_df = code_df[row,], ...))
    })
  }

  restore.point("inbetweenlksjds")

  if (!once_per_runid) {
    ind = match(code_df$runid, runids)
    to_rows = which(!is.na(ind))
    new_code = new_code[ind[to_rows]]
  } else {
    to_rows = rows
  }
  if (append_mode=="overwrite") {
    code_df[[to_col]][to_rows] = new_code
  } else if (append_mode == "left") {
    code_df[[to_col]][to_rows] = paste0(new_code,code_df[[to_col]][to_rows])
  } else if (append_mode == "right") {
    code_df[[to_col]][to_rows] = paste0(code_df[[to_col]][to_rows], new_code)
  } else {
    stop(paste0("unknown append_mode = ", appen_mode))
  }
  code_df

}






#' Replace file paths in cleaned Stata command lines
#'
#' @param cmdline Character vector of cleaned Stata commands (one per line)
#' @param replacement String to insert in place of the file path
#' @return Character vector of commands with paths replaced
replace_stata_cmdline_path = function(cmdline, replacement = '"`r(my_custom_path)\'"', add_clear=TRUE) {
  restore.point("replace_stata_cmdline_paths")

  if (length(replacement)>1 & length(replacement)!= length(cmdline)) {
    stop("cmdline and replacement must have same length.")
  }

  # 1. Parse already-cleaned lines directly into a 'tab' object
  tab = repboxStata::repbox.re.cmdlines.to.tab(cmdline)

  # Because repbox.re.cmdline.to.tab resolves quotes back into the 'tab'
  # dataframe directly, we just provide an empty placeholder dataframe.
  empty_ph = data.frame(ph = character(0), content = character(0))

  # 2. Extract paths into a new placeholder object
  res_paths = repboxStata::replace.files.and.paths.with.ph(tab, empty_ph)

  # 3. If no file paths were found, return the original commands
  if (nrow(res_paths$ph) == 0) {
    return(cmdline)
  }

  # 4. Modify the extracted paths
  fph = res_paths$ph
  fph$content = replacement

  # 5. Re-inject the new paths back into the text
  final_cmds = replace.ph.keep.lines(res_paths$txt, fph)

  add_clear = rep(add_clear, length.out=NROW(final_cmds))
  has_clear = "clear" %in% tolower(tab$opts)
  add_clear = add_clear & !has_clear

  add_str = case_when(
    add_clear & nzchar(tab$opts) ~ " clear",
    add_clear ~ ", clear",
    TRUE ~ ""
  )
  final_cmds = paste0(final_cmds, add_str)


  return(final_cmds)
}



```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/drf_tools.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/io.R
```


drf_make_path_index = function(path_df) {
  path_df$.ROW = 1:NROW(path_df)
  index_df = path_df %>%
    group_by(pid) %>%
    summarize(
      start_row = .ROW[1]
    ) %>%
    bind_rows(tibble(pid=Inf, start_row = NROW(path_df+1)))



}
drf_load_path_index = function(project_dir) {
  index_df = read_rds_or_null(file.path(project_dir, "drf/path_index.Rds"))
  index_df
}

drf_load_path = function(project_dir, pid, index_df = drf_load_path_index(pid))  {

  row = which(index_df$pid==row)
  from = index_df$start_row[row]
  to= index_df$start_row[row+1]-1
  file = file.path(project_dir, "drf/path_df.fst")

  fst::read.fst(file,from = from,to=to)

}

drf_load_path_df = function(project_dir=drf$project_dir, drf=NULL)  {
  file = file.path(project_dir, "drf/path_df.fst")
  if (!file.exists(file)) return(NULL)
  fst::read.fst(file)
}

drf_save_path_df = function(project_dir=drf$project_dir, path_df=drf$path_df, drf)  {
  restore.point("drf_save_path_df")
  index_df = drf_make_path_index(path_df)
  dir = file.path(project_dir, "drf")
  if (!dir.exists(dir)) dir.create(dir)
  saveRDS(index_df, file.path(dir, "path_index.Rds"))

  file = file.path(project_dir, "drf/path_df.fst")
  fst::write.fst(path_df, file)
  return(index_df)

}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/io.R

-----------------------------------------------------------


# FILE: /home/rstudio/repbox/repboxDRF/R/tools.R
```
sec_since_start = function(time_str, start_time_str) {
  restore.point("sec_since_start")
  if (length(start_time_str) != 1L) stop("start_time_str must be length 1.")

  ppidse_hms_sec = function(x) {
    # Fast fixed-position ppidse of "HH:MM:SS"
    h = as.integer(stringi::stri_sub(x, 1L, 2L))
    m = as.integer(stringi::stri_sub(x, 4L, 5L))
    s = as.integer(stringi::stri_sub(x, 7L, 8L))
    3600L * h + 60L * m + s
  }

  t_sec = ppidse_hms_sec(time_str)
  start_sec = ppidse_hms_sec(start_time_str)

  dt = t_sec - start_sec
  dt = dt + 86400L * (dt < 0L)
  dt
}
```
# END OF FILE: /home/rstudio/repbox/repboxDRF/R/tools.R

-----------------------------------------------------------


# Package stata2r (excerpt of R files)


# FILE: /home/rstudio/aicoder/stata2r/DESCRIPTION
```
Package: stata2r
Type: Package
Title: stata2r translation for data manipulation commands
Version: 0.1.0
Author: Sebastian Kranz
Maintainer: Sebastian Kranz <sebastian.kranz@uni-ulm.de>
Description: Experiment: develop package using an ai agent via aicode
License: GPL >= 2.0
Encoding: UTF-8
LazyData: true
Depends: stringi, collapse, dplyr, restorepoint,  repboxUtils
```
# END OF FILE: /home/rstudio/aicoder/stata2r/DESCRIPTION

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/aic_do_test.R
```
examples = function() {
  library(aicoder)
  do_file = "C:/libraries/aicoder/stata2r/inst/cases/custom_1/do1.do"
  aic_stata2r_do_test(aic=NULL, test_dir = "~/aicoder/stata2r/aicoder_work/tests/do1", data_dir = "~/aicoder/stata2r/inst/cases/do1/do_data")

  aic_stata2r_do_test(aic=NULL, test_dir = "~/aicoder/stata2r/aicoder_work/tests/do5", data_dir = "~/aicoder/stata2r/inst/cases/do5/do_data")
}

aic_stata2r_do_test = function(aic, test_dir, data_dir=file.path(test_dir, "do_data"), data_prefix=paste0(basename(test_dir),"-")) {
  restore.point("aic_stata2r_do_test")
  library(aicoder)
  if (is.null(aic)) {
    aic = aicoder::aic_new(is_pkg=FALSE)
  }
  txt = capture.output(err<-try(aic_stata2r_do_test_inner(test_dir, data_dir, data_prefix), silent=TRUE))
  log = out_and_err_txt(txt, err)
  cat(log)
  has_err = is(err, "try-error") | isTRUE(err==FALSE)

  #test_log= list(ok=!has_err,test_name=basename(test_dir), msg="", log=log)
  aic = aic_add_test(aic, test_name=basename(test_dir),show_test = TRUE, ok=!has_err, log=log)
  aic
}

aic_stata2r_do_test_inner = function(test_dir, data_dir, data_prefix="", do_file = paste0(basename(test_dir),".do")) {
  restore.point("aic_stata2r_do_test_inner")
  setwd(test_dir)

  # Set global environment variables for path resolution in translation functions
  assign("data_dir", data_dir, envir = stata2r_env)
  assign("working_dir", test_dir, envir = stata2r_env)
  # Initialize global flag for original order index. This flag will be set to TRUE by t_use or t_collapse.
  assign("has_original_order_idx", FALSE, envir = stata2r_env)

  library(stata2r)
  # Explicitly load dependencies for the test environment
  library(collapse)
  library(dplyr)
  library(stringi)
  library(haven)
  library(tidyr) # For reshape
  library(restorepoint) # If used by translated code or framework
  library(readr) # For destring
  library(labelled) # For decode/encode
  library(stats) # For lm, sd, median etc. (used in t_regress, t_summarize)

  # Suppress dplyr summarise messages during tests
  options(dplyr.summarise_inform = FALSE)

  # do code that will be translated
  do_code = readLines(file.path(test_dir, basename(do_file)), warn=FALSE)
  #cat(do_code, sep="\n")


  cat("\ncmd_df = do_parse(do_code)")
  cmd_df = do_parse(do_code)

  cat("\ncmd_df = mark_data_manip_cmd(cmd_df)\n")
  cmd_df = mark_data_manip_cmd(cmd_df)
  cat("\nstr(cmd_df)\n")
  print(str(cmd_df))

  # Identify variables generated by runiform() or other non-deterministic functions
  non_deterministic_cols = character(0)
  for (i in seq_len(NROW(cmd_df))) {
    if (cmd_df$stata_cmd[i] %in% c("generate", "gen")) {
      rest_of_cmd = cmd_df$rest_of_cmd[i]
      # Extract expression part: `new_var = expression`
      # Strip type if present (e.g. gen double newvar = ...) before matching
      rest_of_cmd_no_type = stringi::stri_replace_first_regex(rest_of_cmd, "^(?:byte|int|long|float|double|str\\d+)\\s+", "")
      match = stringi::stri_match_first_regex(rest_of_cmd_no_type, "^\\s*([^=\\s]+)\\s*=\\s*(.*?)(?:\\s+if\\s+(.*))?$")
      if (!is.na(match[1,1])) {
        new_var = stringi::stri_trim_both(match[1,2])
        stata_expr = stringi::stri_trim_both(match[1,3])
        if (stringi::stri_detect_fixed(stata_expr, "runiform()")) {
          non_deterministic_cols = c(non_deterministic_cols, new_var)
        }
      }
    }
  }


  cat("\n---\n#Translate Stata to R commands... ")
  cmd_df = cmd_df %>% filter(cmd_df$do_code != "")
  r_df = do_to_r(cmd_df$do_code,return_df = TRUE)
  cat("... translation done.")

  env = new.env(parent=globalenv())

  cat("\n---\n# Run translated R commands and compare results\n\n")
  i_df_loop = 1
  log_str = NULL
  for (i_df_loop in seq_len(NROW(r_df))) {
    r_code_to_exec = r_df$r_code[[i_df_loop]]
    original_stata_line_num = r_df$line[[i_df_loop]]
    do_code_original = r_df$do_code[[i_df_loop]]
    # NEW: Get the flag for ignoring row order for this specific command
    ignore_row_order_for_this_line = r_df$ignore_row_order_for_comparison[[i_df_loop]]

    if (is.na(r_code_to_exec)) {
      cat("\n", original_stata_line_num, "do: ", do_code_original, "\n")
      cat("\n", original_stata_line_num, "r:  not translated since not flagged as data manipulation\n")
      next
    } else {
      res = aicoder::run_with_log(code_str=r_code_to_exec, env=env)
      cat("\n", original_stata_line_num,"do: ", do_code_original)
      cat("\n", original_stata_line_num, "r: ", r_code_to_exec, "\n")
      #cat(res$log)

      if (res$has_error) {
        cat("\nError executing R code for Stata line ", original_stata_line_num, ": ", res$log, "\n")
        return(FALSE)
      }
    }

    r_data = env[["data"]]
    if (!is.null(r_data)) {
      dat_file = file.path(data_dir, paste0(data_prefix, original_stata_line_num, ".dta"))
      # Check if reference Stata .dta file exists. If not, skip comparison for this line.
      if (!file.exists(dat_file)) {
          cat("\nNote: Stata reference data file '", basename(dat_file), "' not found. Skipping comparison for Stata line ", original_stata_line_num, ".\n")
          # This implies the command might not produce a .dta in Stata test setup (e.g. summarize, regress)
          # Or it's a line where comparison is not intended.
          next
      }

      do_data = haven::read_dta(dat_file)

      cols_in_r_not_do = setdiff(names(r_data), names(do_data))
      cols_to_remove_from_r_for_comp = setdiff(cols_in_r_not_do, c(non_deterministic_cols, "stata2r_original_order_idx"))

      if (length(cols_to_remove_from_r_for_comp) > 0) {
          cat(paste0("Test data inconsistency: Columns ", paste(cols_to_remove_from_r_for_comp, collapse=", "), " exist in R data but not in Stata reference data (", basename(dat_file), "). Make sure that translation functions remove temporary columns from data or store them in separate temporary variables if needed or as attributes of data."))
          return(FALSE)
          #r_data = dplyr::select(r_data, -dplyr::any_of(cols_to_remove_from_r_for_comp))
      }

      actual_ignore_cols = c(non_deterministic_cols, "stata2r_original_order_idx")
      if (basename(test_dir) == "do2") {
        actual_ignore_cols = c(actual_ignore_cols, "obs_quarter")
      }
      # Pass the new flag to compare_df
      comp = compare_df(do_data, r_data, ignore_cols_values = actual_ignore_cols, ignore_row_order = ignore_row_order_for_this_line)
      if (!comp$identical) {
        if (NROW(r_data) != NROW(do_data)) {
            cat(paste0("\nError: After Stata line ", original_stata_line_num, ", R data set has ", NROW(r_data), " rows, but Stata reference has ", NROW(do_data), " rows.\n"))
        }
        cat("\nError: After Stata line ", original_stata_line_num, ", R data set differs from Stata reference.\n")
        cat("\nData set from Stata (do_df):\n")
        print(str(do_data))
        cat("\nData set from R (r_df):\n")
        print(str(r_data))
        cat("\nDifferences:")
        print(str(comp))
        return(FALSE)
      }
    } else {
      # Only error if 'data' is NULL AND a .dta file for comparison exists for this line.
      # Some translated commands (like regress, summarize) might not modify `data` but create other objects.
      dat_file_check = file.path(data_dir, paste0(data_prefix, original_stata_line_num, ".dta"))
      if (file.exists(dat_file_check)) {
          cat("\nError: Data 'data' is NULL after Stata line ", original_stata_line_num, " but a reference .dta file exists.\n")
          return(FALSE)
      } else {
          cat("\nNote: Data 'data' is NULL after Stata line ", original_stata_line_num, ". No reference .dta file for comparison. Assuming this is expected (e.g., for summarize, regress).\n")
      }
    }
  }
  return(TRUE)
}


out_and_err_txt = function(out, err=NULL) {
  if (is(err,"try-error")) {
    out = c(out,as.character(err))
  }
  paste0(out, collapse="\n")
}

compare_df = function(df1, df2,
                      tol = 5e-5,  # numeric tolerance - Adjusted from 1e-5 to 5e-5 for typical float precision
                      ignore_col_order = FALSE,
                      ignore_row_order = FALSE, # Now this can be TRUE
                      sample_n_diff = 5,            # max rows to show per column
                      ignore_cols_values = character(0)) {
  restore.point("compare_df")
  if (!is.data.frame(df1) || !is.data.frame(df2))
    stop("Both inputs must be data frames.")

  # Always strip Stata attributes from df1 (Stata reference) and df2 (R data)
  # to ensure clean comparison, as R data is also stripped during translation.
  df1 = sfun_strip_stata_attributes(df1)
  df2 = sfun_strip_stata_attributes(df2)

  if(identical(df1, df2)) return(list(identical=TRUE))

  if (ignore_col_order) {
    df1 = df1[, sort(names(df1)), drop = FALSE]
    df2 = df2[, sort(names(df2)), drop = FALSE]
  }
  if (ignore_row_order) {
    df1 = as.data.frame(df1)
    df2 = as.data.frame(df2)
    # Attributes already stripped above
    if (NROW(df1) > 0 && NCOL(df1) > 0) {
      df1 = df1[do.call(order, c(as.list(df1), list(na.last = TRUE))), , drop = FALSE]
    }
    if (NROW(df2) > 0 && NCOL(df2) > 0) {
      df2 = df2[do.call(order, c(as.list(df2), list(na.last = TRUE))), , drop = FALSE]
    }
  }

  out = list(identical=FALSE)

  # Check row counts first and return early if different, without detailed column diffs
  if (NROW(df1) != NROW(df2)) {
    out$row_count_mismatch = paste0("df1 has ", NROW(df1), " rows, df2 has ", NROW(df2), " rows.")
    return(out)
  }


  names_df1_raw = unname(as.character(names(df1)))
  names_df2_raw = unname(as.character(names(df2)))

  names_df1_filtered = setdiff(names_df1_raw, ignore_cols_values)
  names_df2_filtered = setdiff(names_df2_raw, ignore_cols_values)

  missing_in_do_df = setdiff(names_df2_filtered, names_df1_filtered)
  missing_in_r_df = setdiff(names_df1_filtered, names_df2_filtered)
  if (length(missing_in_do_df) + length(missing_in_r_df) > 0)
    out$column_mismatch = list(missing_in_do_df = missing_in_do_df,
                               missing_in_r_df = missing_in_r_df)

  common_cols = intersect(names_df1_filtered, names_df2_filtered)
  if (length(common_cols) == 0 && (length(names_df1_filtered) > 0 || length(names_df2_filtered) > 0)) {
      if (is.null(out$column_mismatch)) {
          out$column_mismatch = list(missing_in_do_df = missing_in_do_df,
                                     missing_in_r_df = missing_in_r_df)
      }
  }

  main_class = function(x) {
    class_val = last(class(x))
    if (class_val=="double") class_val="numeric"
    if (inherits(x, "Date")) class_val = "numeric_date_type" # Keep Date class for comparison
    class_val
  }

  type_df = data.frame(col = common_cols,
                       class_do_df = vapply(df1[common_cols], main_class, character(1)),
                       class_r_df = vapply(df2[common_cols], main_class, character(1)),
                       stringsAsFactors = FALSE)
  type_diff = type_df[type_df$class_do_df != type_df$class_r_df, ]

  type_diff = type_diff[! (type_diff$class_do_df %in% c("integer", "numeric", "numeric_date_type") &
                           type_diff$class_r_df %in% c("integer", "numeric", "numeric_date_type")),]


  if (nrow(type_diff) > 0)
    out$type_mismatch = type_diff

  cols_for_value_comp = common_cols

  value_diffs = lapply(cols_for_value_comp, function(cl) {
    v1 = df1[[cl]]
    v2 = df2[[cl]]

    # Convert to Stata numeric date representation (days since 1960-01-01) for comparison
    if (inherits(v1, "Date")) {
      v1 = as.numeric(v1 - as.Date("1960-01-01"))
    }
    if (inherits(v2, "Date")) {
      v2 = as.numeric(v2 - as.Date("1960-01-01"))
    }
    # If one is numeric (Stata date) and other is R Date (already converted above), no further action.


    if (is.numeric(v1) && is.numeric(v2)) {
      neq = rep(FALSE, length(v1))
      for (k in seq_along(v1)) {
        val1_k = v1[k]
        val2_k = v2[k]

        if (is.na(val1_k) && is.na(val2_k)) {
          neq[k] = FALSE
        } else if (is.infinite(val1_k) && is.infinite(val2_k) && sign(val1_k) == sign(val2_k)) {
          neq[k] = FALSE
        } else if (is.finite(val1_k) && is.finite(val2_k) && abs(val1_k - val2_k) <= tol) {
          neq[k] = FALSE
        } else {
          neq[k] = TRUE
        }
      }

    } else {
      neq = as.character(v1) != as.character(v2) | xor(is.na(v1), is.na(v2))
    }
    which(neq)
  })
  names(value_diffs) = cols_for_value_comp
  value_diffs = value_diffs[lengths(value_diffs) > 0]

  if (length(value_diffs) > 0) {
    sampler = function(idx, cl) {
      head_idx = head(idx, sample_n_diff)
      data.frame(row = head_idx,
                 column = cl,
                 df1_value = as.character(df1[[cl]][head_idx]),
                 df2_value = as.character(df2[[cl]][head_idx]),
                 stringsAsFactors = FALSE)
    }
    diff_tbl = do.call(rbind, Map(sampler, value_diffs, names(value_diffs)))
    rownames(diff_tbl) = NULL
    out$value_mismatch = diff_tbl
  }

  if (length(out) <= 1) {
    return(list(identical=TRUE))
  }
  out
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/aic_do_test.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/aic_stata2r.R
```
example = function() {
  library(aicoder)
  library(files2prompt)
  main_dir = "~/aicoder"
  files = paste0(main_dir, "/stata2r/R/",  c("aic_stata2r.R", "aic_do_test.R","aic_stata_ex.R"))
  for (file in files)  source(file)
  aic = aic_new_stata2r(main_dir)
  #aic = aic_test_stata2r(aic, tests="do5")
  aic = aic_test_stata2r(aic, tests=NULL)
  #undebug(aic_make_prompt_stata2r)
  #aic = aic_make_prompt_stata2r(aic)
  #aic$cfg$tests
  #cat(aic$prompt)
  #aic_view_prompt(aic)
  rstudioapi::navigateToFile("~/aicoder/stata2r/aicoder_work/test_report.txt")


  aic$response_file
  aic = aic_changes_stata2r(aic)


  # Run with Gemini
  for (i in 1:20) {
    library(aicoder)
    main_dir = "~/aicoder"
    files = paste0(main_dir, "/stata2r/R/",  c("aic_stata2r.R", "aic_do_test.R","aic_stata_ex.R"))
    for (file in files)  source(file)
    rgemini::set_gemini_api_key(file="~/aicoder/gemini_key.txt")
    aic = aic_new_stata2r(main_dir)
    aic = aic_test_stata2r(aic)
    if (isTRUE(aic$num_tests_failed==0)) {
      cat("\nAll tests ok!")
      break
    }
    #undebug(aic_make_prompt_stata2r)
    aic = aic_make_prompt_stata2r(aic)

    if (!stri_detect_fixed(aic$prompt, "TEST RESULT")) {
      stop("aic$prompt does not show test results!")
    }
    aic = aic_run_gemini(aic,model = "gemini-2.5-flash-preview-05-20")
    aic = aic_changes_stata2r(aic)
    Sys.sleep(5)
  }


  remotes::install_local("~/aicoder/stata2r",upgrade = "never", force=TRUE)
  do_file = "C:/libraries/aicoder/stata2r/inst/cases/custom_1/do1.do"
}


aic_new_stata2r = function(main_dir) {
  restore.point("aic_new_stata2r")
  main_dir = normalizePath(main_dir)
  repo_dir=file.path(main_dir, "stata2r")
  #do_file = "C:/libraries/aicoder/stata2r/inst/cases/custom_1/do1.do"
  aic = aic_new(
    log_base_dir = file.path(main_dir, "aic_log/stata2r"),
    repo_dir=repo_dir,
    is_pkg=TRUE,
    pat_file = file.path(main_dir, "pat.txt"),
    prompt_config_file = file.path(repo_dir,"f2p_stata2r.toml"),
    do_files = paste0(repo_dir,"/inst/cases/", c("custom_1/do1.do")),
    response_file = file.path(repo_dir, "aicoder_work/ai_resp.txt"),
    temp_dir = file.path(main_dir, "temp"),
    mod_protected_files = c("R/aic_stata2r.R","R/main.R","R/aic_stata_ex.R","R/aic_do_test.R"),
    mod_fixed_dirs = c("r"="R"),
    mod_just_ext = c("r"),
    show_test = FALSE,
    show_failed_test = FALSE
  )

  aic

}

aic_make_prompt_stata2r = function(aic) {
  restore.point("aic_make_prompt_stata2r")
  num_test_failed = aic_num_test_failed(aic)
  num_test = aic_num_test(aic)
  test_str = aic$test_report
  cfg=aic$cfg
  if (!is.null(test_str)) {
    test_str = paste0("\n
#################
# TEST RESULTS
#################\n",
      "In total ", num_test_failed, " of ", num_test, " tests failed:\n\n",
      test_str)
  } else {
    test_str = ""
  }
  cfg$tests = test_str
  task = aic$cfg$task
  if (num_test_failed > 0) {
    task = paste0(task,
"\n# Main task given failed tests

As shown further above, the current code base has failed some tests.
Thus your main task now is to correct the current code base.
Other modifications can be performed once all tests pass correctly.

But note:
- Don't program hacks that would only work for this particular test cases. Write general translation functions that also work also for other test data sets and other do scripts.
- Small rounding errors between R and Stata results are ok, don't try to solve it
by generally rounding your R results.
")
  }
  cfg$task = task
  aic$cfg = cfg
  aic = aic_make_prompt(aic, cfg)
  aic
}

aic_changes_stata2r = function(aic, resp_text = NULL, force_with_lease=TRUE) {
  restore.point("aic_stata2r_update")
  library(aicoder)
  aic_parse_and_commit_changes(aic, resp_text, force_with_lease=force_with_lease)
}

aic_test_stata2r = function(aic, tests = NULL) {
  restore.point("aic_test_stata2r")
  options(error = function() traceback(3))
  aic = aic_clear_tests(aic)
  aic = aic_test_source_r_files(aic)
  if (aic_num_test_failed(aic)>0) {
    cat("\nFailed sourcing R files in stata2r/R")
    aic = aic_tests_finish(aic)
    return(aic)
  }
  cat("\nSourced R files in stata2r/R without error...\n")



  # Build package? Maybe not needed if everything is sourced
  library(aicoder)
  files = list.files(file.path(aic$repo_dir,"R"),glob2rx("*.R"), full.names = TRUE)

  for (file in files) source(file)

  tests_dir = file.path(aic$repo_dir,"aicoder_work", "tests")

  if (is.null(tests))
    tests = c("do1","do2", "do3", "do4", "do5")

  test = "do3"
  for (test in tests) {
    aic = aic_stata2r_do_test(aic=aic, test_dir = paste0("~/aicoder/stata2r/aicoder_work/tests/", test))
    if (!aic$last_test_ok) {
      aic = aic_tests_finish(aic)
      return(aic)
    }
  }
  aic = aic_tests_finish(aic)
  aic
}



aic_stata2r_deploy_tests = function(test_dir) {
  test_dir = "~/aicoder/stata2r/aicoder_work/tests"
  case_dirs = list.dirs("~/aicoder/stata2r/inst/cases",full.names = TRUE, recursive=FALSE)

  # init base files in test dir
  case_dir = case_dirs[3]
  files = list.files(case_dir,full.names = TRUE)
  dest_dir = file.path("~/aicoder/stata2r/aicoder_work/tests", basename(case_dir))
  file.copy(files, dest_dir)

  templ_file = file.path("C:/libraries/aicoder/stata2r/inst/test_tpl/test_tpl.R")
  tpl = read_utf8(templ_file)

  values = list()
  do_file = list.files(dest_dir, glob2rx("*.do"), full.names = TRUE)[1]
  values$do_file = do_file
  values$test_dir = dest_dir

  test_code = files2prompt:::tpl_replace_whisker(tpl, values)
  test_file = paste0(dest_dir, "/test_", basename(dest_dir), ".R")
  write_utf8(test_code, test_file)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/aic_stata2r.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/aic_stata_ex.R
```
# Tools to make Stata example

example = function() {
  do_file = normalizePath("~/aicoder/stata2r/aicoder_work/tests/do1/do1.do")
  run_do_with_data_save(do_file)
  do_file = normalizePath("~/aicoder/stata2r/aicoder_work/tests/do2/do2.do")
  run_do_with_data_save(do_file)

  do_file = normalizePath("~/aicoder/stata2r/aicoder_work/tests/do3/do3.do")
  run_do_with_data_save(do_file)

  do_file = normalizePath("~/aicoder/stata2r/aicoder_work/tests/do4/do4.do")
  run_do_with_data_save(do_file)

  do_file = normalizePath("~/aicoder/stata2r/aicoder_work/tests/do5/do5.do")
  run_do_with_data_save(do_file)
}

run_do_with_data_save = function(do_file) {
  library(haven)
  restore.point("run_do_with_data_save")
  library(dplyr)
  dir = dirname(do_file)
  id = tools::file_path_sans_ext(basename(do_file))
  do_code = readLines(do_file,warn = FALSE)
  setwd(dir)
  lines = seq_along(do_code)
  dta_dir = file.path(dir, "do_data")
  if (!dir.exists(dta_dir)) dir.create(dta_dir)
  do_data_file = paste0(dir,"/do_data/",id,"-", lines,".dta")
  mod_code = paste0(do_code, '\nsave "', do_data_file,'", replace emptyok')
  temp_file = paste0(dir, "/temp_", id, ".do")
  writeLines(mod_code, temp_file)

  run_stata_do(temp_file)

  # make data codes
  dta_files = paste0(dta_dir, "/",id,"-", lines,".dta")
  hashes = sapply(dta_files, function(dta_file) {
    data = read_dta(dta_file)
    data_quick_hash(data)
  })
  hash_df = tibble(doid=id, row=seq_along(hashes), dta_file=basename(dta_files), quick_hash=hashes) %>%
    mutate(hash_changed=!is.true(quick_hash==lag(quick_hash)))
  saveRDS(hash_df, file.path(dir,"data_hashes.Rds"))
}

data_quick_hash = function(df) {
  str = paste0(NROW(df),"|",NCOL(df),"|",
    paste0(names(df), collapse=";")
  )
  row = ceiling(NROW(df)/2)
  if (row>0) {
    el = as.list(df[row,])
    el_str = paste0(sapply(el,function(f) substr(as.character(f)[1],1,5)), collapse=";")
    str = paste0(str,"|",el_str )
  }
  str
}



run_stata_do = function(do.file, stata_bin=get_stata_bin(), set.dir=TRUE, nostop=TRUE, timeout=60*5, verbose=TRUE, use.timeout = !is_windows, is_windows =  .Platform$OS.type == "windows") {
  restore.point("run_stata_do")
  if (set.dir) {
    do.dir = dirname(do.file)
    old.dir = getwd()
    setwd(do.dir)
    file = basename(do.file)
  } else {
    file = do.file
  }


  if (verbose) {
    cat("\n\nRun ", do.file)
  }

  if (is_windows & nostop) {
    cmd = paste0(stata_bin,' /e do "',file,'"', if(nostop) ', nostop')
    #
    # Note: On Windows in BATCH mode no shell commands can be executed.
    # This means rcall cannot be used.
  } else if (is_windows & !nostop) {
    #stop("Need to check windows without nostop")
    cmd = paste0(stata_bin,' /e "',file,'"')
  } else if (!nostop) {
    # Without nostop we must write the code differently (at least on Linux)
    # without explicitly calling the do command
    cmd = paste0(stata_bin,' -b "',file,'"')
    if (!is_empty(timeout) & use.timeout) {
      cmd = paste0("timeout ", timeout," ", cmd)
    }
  } else if (!is_empty(timeout) & use.timeout) {
    cmd = paste0(stata_bin,' -b \'do "',file,'"', if(nostop) ', nostop','\'')
    cmd = paste0("timeout ", timeout," ", cmd)
  } else {
    cmd = paste0(stata_bin,' -b do "',file,'"', if(nostop) ', nostop')
  }

  start.time = Sys.time()

  res = system(cmd)
  end.time = Sys.time()
  runtime = as.numeric(Sys.time()-start.time)

  if (!is_empty(timeout) & !is_windows) {
    if (res != 0) {
      if (verbose) {
        cat(paste0("\n    stopped due to timeout (", timeout, " seconds.)\n"))
      }
      return(list(timeout=TRUE, runtime=runtime))
    }
  } else if (res!=0) {
    stop(paste0("There was an error (code ", res,") when running the Stata command:\n\n", cmd, "\n\nPossible you have to specify the path to the Stata binary by calling set_stata_paths(...)."),call. = FALSE)
  }
  if (verbose) {
    cat(paste0("\n    finished after ", round(runtime,2), " seconds.\n"))
  }
  return(list(timeout=FALSE, runtime=runtime))
}

set_stata_paths = function(stata_bin = NULL,ado_dirs=NULL, base_ado_dir = NULL, stata_dir=NULL, is_windows =  .Platform$OS.type == "windows") {
  if (is_windows) {
    if (!is.null(stata_dir)) {
      if (is.null(stata_bin)) {
        stata_bin = paste0(stata_dir,"/StataSE-64.exe")
      } else if (basename(stata_bin)==stata_bin) {
        stata_bin = paste0(stata_dir, "/", stata_bin)
      }
      if (is.null(base_ado_dir)) {
        base_ado_dir = file.path(stata_dir, "ado","base")
      }
    }
  }
  options(repbox.stata.paths = list(stata_bin=stata_bin, ado_dirs = ado_dirs, base_ado_dir = base_ado_dir))
}

check_stata_paths_and_ado = function(is_windows = .Platform$OS.type == "windows", check_base_ado_dir = FALSE, on_fail = c("error","warn","msg","silent")[1]) {
  restore.point("check_stata_paths_and_ado")

  p = getOption("repbox.stata.paths")
  if (on_fail=="error") {
    fail_fun = function(...) stop(paste0(...),call. = FALSE)
  } else if (on_fail=="warn") {
    fail_fun = function(...) warning(paste0(...))
  } else if (on_fail=="msg") {
    fail_fun = function(...) cat(paste0(...))
  } else {
    fail_fun = function(...) {}
  }

  if (is.null(p) & is_windows) {
    fail_fun("On windows you must set custom stata paths. Please call set_stata_paths")
    return(FALSE)
  }
  ok = TRUE
  stata_bin = get_stata_bin()
  if (basename(stata_bin)!=stata_bin) {
    if (!file.exists(stata_bin)) {
      ok = FALSE
      fail_fun(paste0("The stata binary ", stata_bin, " could not be found."))
    }
  }

  dir = ado_dirs = get_ado_dirs()
  if (!any(dir.exists(dir))) {
    ok = FALSE
    fail_fun(paste0("The modules ado directories ",paste0(dir, collapse=", "), " do not all exist."))
  }

  if (check_base_ado_dir) {
    dir = get_base_ado_dir()
    if (!dir.exists(dir)) {
      ok = FALSE
      fail_fun(paste0("The base ado directory ",dir, " does not exist."))
    }
  }


  if (ok) {
    required_ado = c("parmest.ado",basename(list_repbox_ado_files(only_required=TRUE)))
    initials = substring(required_ado,1,1)
    exists = rep(FALSE, length(required_ado))
    for (dir in ado_dirs) {
      exists = exists |
        file.exists(paste0(dir,"/",required_ado)) |
        file.exists(paste0(dir,"/",initials,"/",required_ado))
    }
    if (!all(exists)) {
      ok = FALSE
      msg = paste0("\nNot all repbox-specific Stata ado files can be found in your specified ado directories:\n\n  ", paste0(ado_dirs, collapse="\n  "), "\n\nPlease call copy_repbox_ado_files(ado_dir) to copy the required ado files.")
      fail_fun(msg)
    }
  }

  return(ok)
}

get_stata_bin = function(default = "stata-se") {
  res = getOption("repbox.stata.paths")$stata_bin
  if (is.null(res)) return(default)
  return(res)
}

is_empty = function (x) {
  if (is.null(x) | all(is.na(x)))
    return(TRUE)
  if (isTRUE(x == ""))
    return(TRUE)
  return(FALSE)
}

is.true = function (x)
{
  val = x == TRUE
  val[is.na(x)] = FALSE
  val
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/aic_stata_ex.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/do_cmd_to_r.R
```
# r_obj will be a single row tibble
# at least with the field r_code
# r_obj will be a single row tibble
# at least with the field r_code
do_cmd_to_r = function(cmd_obj, line, cmd_df) {
  restore.point("do_cmd_to_r")

  if (!cmd_obj$do_translate || is.na(cmd_obj$stata_cmd)) {
    return(data.frame(
      line = line,
      r_code = NA_character_,
      do_code = cmd_obj$do_code,
      stata_translation_error = NA_character_,
      ignore_row_order_for_comparison = cmd_obj$will_ignore_row_order_for_comparison,
      stringsAsFactors = FALSE
    ))
  }

  r_code = NA_character_
  stata_translation_error = NA_character_

  translation_context = list(
    is_by_group = cmd_obj$is_by_prefix,
    is_quietly_prefix = cmd_obj$is_quietly_prefix,
    is_capture_prefix = cmd_obj$is_capture_prefix,
    is_xi_prefix = cmd_obj$is_xi_prefix,
    is_bysort_prefix = if ("is_bysort_prefix" %in% names(cmd_obj)) cmd_obj$is_bysort_prefix else FALSE
  )

  rest_of_cmd_clean = ifelse(is.na(cmd_obj$rest_of_cmd), "", cmd_obj$rest_of_cmd)
  stata_command = cmd_obj$stata_cmd

  res = tryCatch({
    r_code_translated = switch(stata_command,
      "use" = t_use(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "generate" = t_generate(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "gen" = t_generate(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "replace" = t_replace(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "summarize" = t_summarize(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "su" = t_summarize(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "egen" = t_egen(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "sort" = t_sort(rest_of_cmd_clean, cmd_obj, cmd_df, line, type = "sort"),
      "gsort" = t_sort(rest_of_cmd_clean, cmd_obj, cmd_df, line, type = "gsort"),
      "drop" = t_drop(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "keep" = t_keep(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "collapse" = t_collapse(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "rename" = t_rename(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "save" = t_save(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "tempfile" = t_tempfile(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "merge" = t_merge(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "append" = t_append(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "reshape" = t_reshape(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "recode" = t_recode(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "order" = t_order(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "expand" = t_expand(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "duplicates" = t_duplicates(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "encode" = t_encode(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "decode" = t_decode(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "destring" = t_destring(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "preserve" = t_preserve_restore(cmd_obj, type = "preserve"),
      "restore" = t_preserve_restore(cmd_obj, type = "restore"),
      "format" = t_format(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "label" = t_label(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "compress" = t_compress(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "regress" = t_regress(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "areg" = t_areg(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "xtreg" = t_xtreg(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "probit" = t_probit(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "reghdfe" = t_reghdfe(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "logit" = t_logit(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "ivregress" = t_ivregress(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "xi" = t_xi(rest_of_cmd_clean, cmd_obj, cmd_df, line, translation_context),
      "scalar" = t_scalar(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      "sc" = t_scalar(rest_of_cmd_clean, cmd_obj, cmd_df, line),
      paste0("# Stata command '", cmd_obj$stata_cmd_original, " ", rest_of_cmd_clean, "' not yet fully translated.")
    )

    if (is.null(r_code_translated)) {
      r_code_translated = paste0("# Stata command '", cmd_obj$stata_cmd_original, " ", rest_of_cmd_clean, "' (", stata_command, ") translation not implemented.")
    }

    if (isTRUE(translation_context$is_bysort_prefix)) {
      sort_vars = character(0)

      if (!is.na(cmd_obj$by_group_vars) && cmd_obj$by_group_vars != "") {
        sort_vars = c(sort_vars, stringi::stri_split_fixed(cmd_obj$by_group_vars, ",")[[1]])
      }
      if (!is.na(cmd_obj$by_sort_vars) && cmd_obj$by_sort_vars != "") {
        sort_vars = c(sort_vars, stringi::stri_split_fixed(cmd_obj$by_sort_vars, ",")[[1]])
      }

      sort_vars = stringi::stri_trim_both(sort_vars)
      sort_vars = sort_vars[sort_vars != "" & !is.na(sort_vars)]

      if (length(sort_vars) > 0) {
        sort_code = paste0(
          "data = scmd_sort(data = data, varlist_str = ",
          quote_for_r_literal(paste(sort_vars, collapse = " ")),
          ", type = \"sort\")"
        )
        r_code_translated = paste(sort_code, r_code_translated, sep = "\n")
      }
    }

    list(r_code = r_code_translated, stata_translation_error = NA_character_)
  }, error = function(e) {
    list(
      r_code = paste0("# Translation failed for: ", cmd_obj$do_code, "\n# Error: ", e$message),
      stata_translation_error = e$message
    )
  })

  r_obj = data.frame(
    line = line,
    r_code = res$r_code,
    do_code = cmd_obj$do_code,
    stata_translation_error = res$stata_translation_error,
    ignore_row_order_for_comparison = cmd_obj$will_ignore_row_order_for_comparison,
    stringsAsFactors = FALSE
  )
  return(r_obj)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/do_cmd_to_r.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/do_parse.R
```
do_parse = function(do_code) {
  if (is.list(do_code)) {
    do_code = unlist(do_code)
  }
  if (!is.character(do_code)) {
    do_code = as.character(do_code)
  }

  num_lines = length(do_code)
  if (num_lines == 0) {
    return(data.frame(
      line = integer(0),
      do_code = character(0),
      stata_cmd_original = character(0),
      stata_cmd = character(0),
      rest_of_cmd = character(0),
      is_by_prefix = logical(0),
      is_bysort_prefix = logical(0),
      by_group_vars = character(0),
      by_sort_vars = character(0),
      is_quietly_prefix = logical(0),
      is_capture_prefix = logical(0),
      is_xi_prefix = logical(0),
      do_translate = logical(0),
      is_mod = logical(0),
      need_e_sample = logical(0),
      need_xi = logical(0),
      need_e_results = logical(0),
      need_r_results = logical(0),
      stata_translation_error = character(0),
      e_results_needed = I(vector("list", 0)),
      r_results_needed = I(vector("list", 0)),
      will_have_original_order_idx = logical(0),
      will_ignore_row_order_for_comparison = logical(0),
      stringsAsFactors = FALSE
    ))
  }

  parsed_info = parse_stata_command_lines(do_code)

  cmd_df = data.frame(
    line = seq_len(num_lines),
    do_code = do_code,
    stata_cmd_original = parsed_info$stata_cmd_original,
    stata_cmd = parsed_info$stata_cmd,
    rest_of_cmd = parsed_info$rest_of_cmd,
    is_by_prefix = parsed_info$is_by_prefix,
    is_bysort_prefix = parsed_info$is_bysort_prefix,
    by_group_vars = parsed_info$by_group_vars,
    by_sort_vars = parsed_info$by_sort_vars,
    is_quietly_prefix = parsed_info$is_quietly_prefix,
    is_capture_prefix = parsed_info$is_capture_prefix,
    is_xi_prefix = parsed_info$is_xi_prefix,
    stata_translation_error = NA_character_,
    will_ignore_row_order_for_comparison = FALSE,
    stringsAsFactors = FALSE
  )

  cmd_df$e_results_needed = I(replicate(nrow(cmd_df), character(0), simplify = FALSE))
  cmd_df$r_results_needed = I(replicate(nrow(cmd_df), character(0), simplify = FALSE))
  cmd_df$will_have_original_order_idx = rep(FALSE, NROW(cmd_df))
  cmd_df$do_translate = rep(FALSE, NROW(cmd_df))
  cmd_df$is_mod = rep(FALSE, NROW(cmd_df))
  cmd_df$need_e_sample = rep(FALSE, NROW(cmd_df))
  cmd_df$need_xi = rep(FALSE, NROW(cmd_df))
  cmd_df$need_e_results = rep(FALSE, NROW(cmd_df))
  cmd_df$need_r_results = rep(FALSE, NROW(cmd_df))

  return(cmd_df)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/do_parse.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/if_in.R
```
# FILE: R/if_in.R

#' Parse standard Stata if/in components from the end of a string
#' @param str The raw Stata command string (after options have been removed)
#' @return A list with `base_str`, `if_str`, and `in_str`
s2r_parse_if_in = function(str) {
  restore.point("s2r_parse_if_in")
  res = list(base_str = str, if_str = NA_character_, in_str = NA_character_)
  if (is.na(str) || trimws(str) == "") return(res)

  # Extract `in` condition
  in_match = stringi::stri_match_last_regex(res$base_str, "\\b(?:in)\\s+(.*)$")
  if (!is.na(in_match[1,1])) {
    res$in_str = stringi::stri_trim_both(in_match[1,2])
    res$base_str = stringi::stri_trim_both(stringi::stri_replace_last_fixed(res$base_str, in_match[1,1], ""))
  }

  # Extract `if` condition
  if_match = stringi::stri_match_last_regex(res$base_str, "\\b(?:if)\\s+(.*)$")
  if (!is.na(if_match[1,1])) {
    res$if_str = stringi::stri_trim_both(if_match[1,2])
    res$base_str = stringi::stri_trim_both(stringi::stri_replace_last_fixed(res$base_str, if_match[1,1], ""))
  }

  return(res)
}

#' Normalize translated condition strings for runtime evaluation
#'
#' Translated expressions may contain dplyr helpers such as
#' dplyr::row_number() or dplyr::n(), which are valid inside mutate/filter
#' but not when evaluated directly via eval(). For runtime if/in evaluation
#' we replace them by explicit helper symbols backed by concrete vectors/scalars.
#'
#' @param r_cond The translated R condition string
#' @return A condition string that can be safely evaluated with eval()
s2r_prepare_runtime_cond = function(r_cond) {
  restore.point("s2r_prepare_runtime_cond")
  if (is.na(r_cond) || r_cond == "") return(r_cond)

  out = r_cond

  # Main translations produced by translate_stata_expression_to_r()
  out = stringi::stri_replace_all_fixed(out, "dplyr::row_number()", ".stata_row_index")
  out = stringi::stri_replace_all_fixed(out, "dplyr::n()", ".stata_n_rows")

  # Defensive fallback in case untranslated special tokens survive
  out = stringi::stri_replace_all_regex(out, "\\b_n\\b", ".stata_row_index")
  out = stringi::stri_replace_all_regex(out, "\\b_N\\b", ".stata_n_rows")

  return(out)
}

#' Evaluate a Stata condition string at runtime, returning a boolean vector
s2r_eval_cond = function(data, r_cond, envir = parent.frame()) {
  restore.point("s2r_eval_cond")
  if (is.na(r_cond) || r_cond == "") return(rep(TRUE, NROW(data)))

  r_cond = s2r_prepare_runtime_cond(r_cond)

  expr = base::parse(text = r_cond)
  used_vars = all.vars(expr)
  data_cols = names(data)

  eval_list = s2r_setup_eval_list(data)
  eval_list[[".stata_row_index"]] = seq_len(NROW(data))
  eval_list[[".stata_n_rows"]] = NROW(data)

  reserved = c(s2r_eval_reserved_words(), ".stata_row_index", ".stata_n_rows")

  for (v in used_vars) {
    if (!(v %in% c(data_cols, reserved))) {
      mcols = data_cols[startsWith(data_cols, v)]
      if (length(mcols) == 1) {
        eval_list[[v]] = to_stata_na(data[[mcols[1]]])
      } else if (length(mcols) > 1) {
        stop(paste("Ambiguous abbreviation in condition:", v))
      }
    }
  }

  cond_val = base::eval(expr, envir = eval_list, enclos = envir)
  return(dplyr::coalesce(as.logical(cond_val), FALSE))
}

#' Evaluate a Stata 'in' range string at runtime, returning matched indices
s2r_eval_range = function(data, r_range) {
  restore.point("s2r_eval_range")
  if (is.na(r_range) || r_range == "") return(integer(0))

  idx = base::eval(base::parse(text = r_range))
  idx = idx[idx >= 1 & idx <= NROW(data)]
  return(idx)
}

#' Safely evaluate if/in conditions at runtime for row keeping
#' @param data The dataframe
#' @param r_if_cond The translated R condition string
#' @param r_in_range The translated R range string
#' @param envir The enclosing environment for evaluation
#' @return The subsetted dataframe
s2r_eval_if_in = function(data, r_if_cond = NA_character_, r_in_range = NA_character_, envir = parent.frame()) {
  restore.point("seval_if_in")

  if (!is.na(r_if_cond) && r_if_cond != "") {
    cond_val = s2r_eval_cond(data, r_if_cond, envir = envir)
    data = data[cond_val, , drop = FALSE]
  }

  if (!is.na(r_in_range) && r_in_range != "") {
    idx = s2r_eval_range(data, r_in_range)
    data = data[idx, , drop = FALSE]
  }

  return(data)
}

s2r_in_str_to_r_range_str = function(in_str) {
  if (is.null(in_str) | is.na(in_str)) return(NA_character_)

  range_match = stringi::stri_match_first_regex(in_str, "^(\\d+)(?:/(\\d+))?$")
  if (!is.na(range_match[1,1])) {
    start_row = range_match[1,2]
    end_row = range_match[1,3]
    if (is.na(end_row)) {
      r_in_range = start_row
    } else {
      r_in_range = paste0(start_row, ":", end_row)
    }
  } else {
    r_in_range = paste0("# keep in range '", in_str, "' not fully translated.")
  }

  r_in_range
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/if_in.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/main.R
```
# This R file shall not be changed by the AI coding agent

# do_code is a text file with one line per stata command line
# there are no comments
do_to_r = function(do_code, return_df = FALSE, timevar = NULL, panelvar = NULL, tdelta = 1,..., handle_erb=TRUE) {
  restore.point("do_to_r")
  do_code = stringi::stri_split_fixed(do_code, "\n")

  # transforms do_code to a dataframe with
  # one row for each code line possible
  # perform some preparsing
  # the field do_code can contain the original code
  cmd_df = do_parse(do_code)

  # will add field "do_translate"
  # if FALSE the stata command does not modify the data set
  # and can be ignored
  cmd_df = mark_data_manip_cmd(cmd_df)

  # do_cmd_to_r now always returns a data.frame, even on error
  r_df = dplyr::bind_rows(lapply(seq_len(NROW(cmd_df)), function(i)  {
    cmd_obj = cmd_df[i,]
    # r_obj will be a single row tibble
    # at least with the field r_code
    r_obj = do_cmd_to_r(cmd_obj=cmd_obj,line=i, cmd_df=cmd_df)
    r_obj
  }))

  r_df = s2r_resolve_ts_operators(r_df, timevar, panelvar, tdelta)

  if (return_df) return(r_df)


  # r_code should be extracted from r_df$r_code
  r_code = paste0(r_df$r_code, collapse="\n")
  return(list(r_df=r_df, r_code=r_code))
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/main.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/mark_data_manip_cmd.R
```
s2r_cmd_resets_row_order_compare = function(cmd_obj) {
  stata_cmd = cmd_obj$stata_cmd[1]
  if (is.na(stata_cmd) || stata_cmd == "") return(FALSE)

  stata_cmd %in% c("use", "collapse", "reshape")
}

s2r_cmd_can_change_row_order = function(cmd_obj) {
  stata_cmd = cmd_obj$stata_cmd[1]
  if (is.na(stata_cmd) || stata_cmd == "") return(FALSE)

  if (stata_cmd %in% c("sort", "gsort")) {
    return(TRUE)
  }

  isTRUE(cmd_obj$is_bysort_prefix[1])
}

mark_data_manip_cmd = function(cmd_df) {
  restore.point("mark_data_manip_cmd")

  if (NROW(cmd_df) == 0) {
    cmd_df = s2r_check_mod_df(cmd_df)
    if (!("will_have_original_order_idx" %in% names(cmd_df))) cmd_df$will_have_original_order_idx = logical(0)
    if (!("will_ignore_row_order_for_comparison" %in% names(cmd_df))) cmd_df$will_ignore_row_order_for_comparison = logical(0)
    return(cmd_df)
  }

  cmd_df = s2r_check_mod_df(cmd_df)

  if (!("will_have_original_order_idx" %in% names(cmd_df))) {
    cmd_df$will_have_original_order_idx = rep(FALSE, NROW(cmd_df))
  }
  cmd_df$will_ignore_row_order_for_comparison = rep(FALSE, NROW(cmd_df))

  current_has_order_idx_at_translation_time = FALSE
  row_order_may_differ_from_stata = FALSE

  for (i in seq_len(NROW(cmd_df))) {
    cmd_obj = cmd_df[i, , drop = FALSE]

    if (s2r_cmd_resets_row_order_compare(cmd_obj)) {
      row_order_may_differ_from_stata = FALSE
    }

    if (cmd_df$do_translate[i]) {
      if (cmd_df$stata_cmd[i] %in% c("use", "collapse", "reshape")) {
        current_has_order_idx_at_translation_time = TRUE
      } else if (cmd_df$stata_cmd[i] %in% c("drop", "keep", "expand", "merge", "append", "order")) {
        current_has_order_idx_at_translation_time = current_has_order_idx_at_translation_time
      } else if (cmd_df$stata_cmd[i] %in% c("preserve")) {
        current_has_order_idx_at_translation_time = current_has_order_idx_at_translation_time
      } else if (cmd_df$stata_cmd[i] %in% c("restore")) {
        current_has_order_idx_at_translation_time = current_has_order_idx_at_translation_time
      }
    }
    cmd_df$will_have_original_order_idx[i] = current_has_order_idx_at_translation_time

    if (s2r_cmd_can_change_row_order(cmd_obj)) {
      row_order_may_differ_from_stata = TRUE
    }

    cmd_df$will_ignore_row_order_for_comparison[i] = row_order_may_differ_from_stata
  }

  return(cmd_df)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/mark_data_manip_cmd.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/s2r_check_mod.R
```
# Public helper and internal engine for identifying commands that matter for later data preparation

s2r_check_mod = function(stata_code) {
  restore.point("s2r_check_mod")

  if (length(stata_code) == 1 && is.character(stata_code) && dplyr::coalesce(stringi::stri_detect_fixed(stata_code, "\n"), FALSE)) {
    stata_code = stringi::stri_split_fixed(stata_code, "\n")[[1]]
  }
  if (is.list(stata_code)) {
    stata_code = unlist(stata_code)
  }
  if (!is.character(stata_code)) {
    stata_code = as.character(stata_code)
  }

  cmd_df = do_parse(stata_code)
  s2r_check_mod_df(cmd_df)
}

s2r_check_mod_df = function(cmd_df) {
  restore.point("s2r_check_mod_df")

  n_rows = NROW(cmd_df)
  if (n_rows == 0) {
    if (!("is_mod" %in% names(cmd_df))) cmd_df$is_mod = logical(0)
    if (!("do_translate" %in% names(cmd_df))) cmd_df$do_translate = logical(0)
    if (!("need_e_sample" %in% names(cmd_df))) cmd_df$need_e_sample = logical(0)
    if (!("need_xi" %in% names(cmd_df))) cmd_df$need_xi = logical(0)
    if (!("need_e_results" %in% names(cmd_df))) cmd_df$need_e_results = logical(0)
    if (!("need_r_results" %in% names(cmd_df))) cmd_df$need_r_results = logical(0)
    if (!("e_results_needed" %in% names(cmd_df))) cmd_df$e_results_needed = I(vector("list", 0))
    if (!("r_results_needed" %in% names(cmd_df))) cmd_df$r_results_needed = I(vector("list", 0))
    return(cmd_df)
  }

  if (!("is_xi_prefix" %in% names(cmd_df))) cmd_df$is_xi_prefix = rep(FALSE, n_rows)

  cmd_df$is_mod = rep(FALSE, n_rows)
  cmd_df$do_translate = rep(FALSE, n_rows)
  cmd_df$need_e_sample = rep(FALSE, n_rows)
  cmd_df$need_xi = rep(FALSE, n_rows)
  cmd_df$need_e_results = rep(FALSE, n_rows)
  cmd_df$need_r_results = rep(FALSE, n_rows)

  # Commands that are inherently data-modifying are always kept.
  cmd_df$is_mod = !is.na(cmd_df$stata_cmd) & (cmd_df$stata_cmd %in% stata_data_manip_cmds)

  # Prepare string vector to avoid slow dplyr::coalesce inside the loop
  rest_of_cmd_vec = cmd_df$rest_of_cmd
  rest_of_cmd_vec[is.na(rest_of_cmd_vec)] = ""

  # Vectorized extraction of all e() and r() macros at once
  e_matches_list = stringi::stri_match_all_regex(rest_of_cmd_vec, "e\\(([^)]+)\\)")
  r_matches_list = stringi::stri_match_all_regex(rest_of_cmd_vec, "r\\(([^)]+)\\)")

  # Precompute logical vectors for fast lookup
  cmd_is_est = !is.na(cmd_df$stata_cmd) & (cmd_df$stata_cmd %in% stata_estimation_cmds)
  cmd_is_r_res = !is.na(cmd_df$stata_cmd) & (cmd_df$stata_cmd %in% stata_r_result_cmds)

  potential_e_results_produced = c("e(sample)", "e(N)", "e(r2)", "e(df_r)", "e(rmse)", "e(b)", "e(V)")
  potential_r_results_produced = c("r(N)", "r(mean)", "r(sd)", "r(min)", "r(max)", "r(sum)", "r(p50)")

  e_results_needed_list = vector("list", n_rows)
  r_results_needed_list = vector("list", n_rows)

  active_needed_e_results = character(0)
  active_needed_r_results = character(0)

  # Backward pass to resolve macro dependencies
  for (i in n_rows:1) {
    # Check if current command fulfills needed macros
    if (cmd_is_est[i]) {
      intersect_e = intersect(potential_e_results_produced, active_needed_e_results)
      if (length(intersect_e) > 0) {
        cmd_df$is_mod[i] = TRUE
        e_results_needed_list[[i]] = intersect_e
        active_needed_e_results = setdiff(active_needed_e_results, potential_e_results_produced)
      }
    }

    if (cmd_is_r_res[i]) {
      intersect_r = intersect(potential_r_results_produced, active_needed_r_results)
      if (length(intersect_r) > 0) {
        cmd_df$is_mod[i] = TRUE
        r_results_needed_list[[i]] = intersect_r
        active_needed_r_results = setdiff(active_needed_r_results, potential_r_results_produced)
      }
    }

    # Add new requirements from this command
    mat_e = e_matches_list[[i]]
    if (!is.na(mat_e[1,1])) {
      used_e_macros = unique(paste0("e(", mat_e[,2], ")"))
      active_needed_e_results = union(active_needed_e_results, used_e_macros)
    }

    mat_r = r_matches_list[[i]]
    if (!is.na(mat_r[1,1])) {
      used_r_macros = unique(paste0("r(", mat_r[,2], ")"))
      active_needed_r_results = union(active_needed_r_results, used_r_macros)
    }
  }

  cmd_df$e_results_needed = I(e_results_needed_list)
  cmd_df$r_results_needed = I(r_results_needed_list)

  # Xi side effects from xi-prefixed estimation commands
  idx_xi_est = which(cmd_df$is_xi_prefix & cmd_is_est)
  if (length(idx_xi_est) > 0) {
    do_code_vec = cmd_df$do_code
    do_code_vec[is.na(do_code_vec)] = ""

    for (i in idx_xi_est) {
      parsed_est = s2r_p_estimation_cmd(rest_of_cmd_vec[i], estimator = cmd_df$stata_cmd[i])
      xi_prefixes = s2r_xi_specs_to_prefixes(parsed_est$xi_specs)

      need_xi_i = FALSE
      if (length(xi_prefixes) > 0 && i < n_rows) {
        later_lines = do_code_vec[(i + 1):n_rows]

        # Fast vectorized check across all later lines at once
        if (any(stringi::stri_detect_fixed(later_lines, "_I*"))) {
          need_xi_i = TRUE
        } else {
          for (pref in xi_prefixes) {
            if (any(stringi::stri_detect_fixed(later_lines, pref))) {
              need_xi_i = TRUE
              break
            }
          }
        }
      }

      cmd_df$need_xi[i] = need_xi_i
      if (need_xi_i) {
        cmd_df$is_mod[i] = TRUE
      }
    }
  }

  cmd_df$need_e_sample = vapply(e_results_needed_list, function(x) "e(sample)" %in% x, logical(1))
  cmd_df$need_e_results = lengths(e_results_needed_list) > 0
  cmd_df$need_r_results = lengths(r_results_needed_list) > 0

  # Final explicit overrides (vectorized)
  is_non_manip = !is.na(cmd_df$stata_cmd) & (cmd_df$stata_cmd %in% stata_non_data_manip_cmds)
  keep_due_to_results = cmd_df$need_e_results | cmd_df$need_r_results | cmd_df$need_xi

  override_idx = is_non_manip & !keep_due_to_results
  if (any(override_idx)) {
    cmd_df$is_mod[override_idx] = FALSE
  }

  cmd_df$is_mod[is.na(cmd_df$stata_cmd)] = FALSE

  is_standalone_clear = !is.na(cmd_df$stata_cmd) & cmd_df$stata_cmd == "clear" & (rest_of_cmd_vec == "")
  if (any(is_standalone_clear)) {
    cmd_df$is_mod[is_standalone_clear] = TRUE
  }

  cmd_df$do_translate = cmd_df$is_mod
  return(cmd_df)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/s2r_check_mod.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/s2r_estimation_utils.R
```
# Shared helpers for estimation commands and xi-prefixed estimation side effects

s2r_chr_vec_to_r = function(x) {
  restore.point("s2r_chr_vec_to_r")
  if (length(x) == 0) {
    return("character(0)")
  }
  paste0("c(", paste(vapply(x, quote_for_r_literal, character(1)), collapse = ", "), ")")
}

s2r_extract_xi_specs = function(model_terms) {
  restore.point("s2r_extract_xi_specs")
  specs = list()
  if (length(model_terms) == 0) return(specs)

  for (term in model_terms) {
    term = stringi::stri_trim_both(term)
    if (is.na(term) || term == "") next

    inter_match = stringi::stri_match_first_regex(term, "^i\\.([A-Za-z_][A-Za-z0-9_]*)\\*i\\.([A-Za-z_][A-Za-z0-9_]*)$")
    if (!is.na(inter_match[1,1])) {
      specs[[length(specs) + 1]] = list(var1 = inter_match[1,2], var2 = inter_match[1,3])
      next
    }

    single_match = stringi::stri_match_first_regex(term, "^i\\.([A-Za-z_][A-Za-z0-9_]*)$")
    if (!is.na(single_match[1,1])) {
      specs[[length(specs) + 1]] = list(var1 = single_match[1,2], var2 = NA_character_)
      next
    }
  }

  specs
}

s2r_model_term_to_vars = function(term) {
  restore.point("s2r_model_term_to_vars")
  if (is.na(term) || term == "") return(character(0))

  pieces = stringi::stri_split_regex(term, "#|\\*")[[1]]
  vars = character(0)

  for (piece in pieces) {
    piece = stringi::stri_trim_both(piece)
    if (piece == "") next

    while (TRUE) {
      m = stringi::stri_match_first_regex(piece, "^[A-Za-z0-9]+\\.(.+)$")
      if (is.na(m[1,1])) break
      piece = m[1,2]
    }

    if (stringi::stri_detect_regex(piece, "^[A-Za-z_][A-Za-z0-9_]*$")) {
      vars = c(vars, piece)
    }
  }

  unique(vars)
}

s2r_p_estimation_cmd = function(rest_of_cmd, estimator = NA_character_) {
  restore.point("s2r_p_estimation_cmd")

  parts = stringi::stri_match_first_regex(stringi::stri_trim_both(rest_of_cmd), "^\\s*(.*?)(?:,\\s*(.*))?$")
  main_part = stringi::stri_trim_both(parts[1,2])
  options_part = stringi::stri_trim_both(parts[1,3])

  parsed_if = s2r_parse_if_in(main_part)
  model_part = parsed_if$base_str

  tokens = stringi::stri_split_regex(stringi::stri_trim_both(model_part), "\\s+")[[1]]
  tokens = tokens[tokens != ""]

  dep_var = if (length(tokens) > 0) tokens[1] else NA_character_
  indep_terms = if (length(tokens) > 1) tokens[-1] else character(0)

  absorb_vars = character(0)
  cluster_vars = character(0)
  if (!is.na(options_part) && options_part != "") {
    absorb_match = stringi::stri_match_first_regex(options_part, "\\babsorb\\s*\\(([^)]+)\\)")
    if (!is.na(absorb_match[1,1])) {
      absorb_vars = stringi::stri_split_regex(stringi::stri_trim_both(absorb_match[1,2]), "\\s+")[[1]]
      absorb_vars = absorb_vars[absorb_vars != ""]
    }

    vce_match = stringi::stri_match_first_regex(options_part, "\\bvce\\s*\\(([^)]+)\\)")
    if (!is.na(vce_match[1,1])) {
      vce_opts = stringi::stri_split_regex(stringi::stri_trim_both(vce_match[1,2]), "\\s+")[[1]]
      vce_opts = vce_opts[vce_opts != ""]
      if (length(vce_opts) > 1 && vce_opts[1] == "cluster") {
        cluster_vars = vce_opts[-1]
      }
    }
  }

  xi_specs = s2r_extract_xi_specs(indep_terms)
  model_vars = unique(unlist(c(
    lapply(indep_terms, s2r_model_term_to_vars),
    lapply(absorb_vars, s2r_model_term_to_vars),
    lapply(cluster_vars, s2r_model_term_to_vars)
  )))

  list(
    estimator = estimator,
    dep_var = dep_var,
    indep_terms = indep_terms,
    model_vars = model_vars,
    absorb_vars = absorb_vars,
    xi_specs = xi_specs,
    if_str = parsed_if$if_str,
    options = options_part
  )
}

s2r_xi_specs_to_prefixes = function(xi_specs) {
  restore.point("s2r_xi_specs_to_prefixes")
  prefixes = character(0)
  if (length(xi_specs) == 0) return(prefixes)

  for (spec in xi_specs) {
    if (is.null(spec$var2) || is.na(spec$var2) || spec$var2 == "") {
      base_name = get_xi_base_name(spec$var1)
    } else {
      base_name = get_xi_interaction_basename(spec$var1, spec$var2)
    }
    prefixes = c(prefixes, paste0("_I", base_name, "_"))
  }

  unique(prefixes)
}

s2r_line_uses_xi_prefixes = function(line_text, xi_prefixes) {
  restore.point("s2r_line_uses_xi_prefixes")
  if (is.na(line_text) || line_text == "" || length(xi_prefixes) == 0) return(FALSE)

  if (dplyr::coalesce(stringi::stri_detect_fixed(line_text, "_I*"), FALSE)) {
    return(TRUE)
  }

  any(vapply(xi_prefixes, function(pref) {
    dplyr::coalesce(stringi::stri_detect_fixed(line_text, pref), FALSE)
  }, logical(1)))
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/s2r_estimation_utils.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/s2r_ts_op.R
```
# FILE: stata2r/R/s2r_ts_op.R

#' Resolve Time-Series Operators in Translated R Code
#' Processes a translation dataframe sequentially to track xtset/tsset state
#' and replaces TS operators with native collapse calls.
s2r_resolve_ts_operators = function(r_df, timevar = NULL, panelvar = NULL, tdelta = 1) {
  restore.point("s2r_resolve_ts_operators")
  # We assume r_df has columns like `cmdline` (original Stata) and `r_code` (translated R)
  cmd_col = intersect(c("do_code","stata_code","cmdlin"), names(r_df))[1]

  for (i in seq_len(nrow(r_df))) {
    stata_cmd = trimws(r_df[[cmd_col]][i])

    # 1. Update TS state if an xtset or tsset command is encountered
    if (grepl("^(xtset|tsset)\\b", stata_cmd, ignore.case = TRUE)) {
      hints = s2r_parse_xtset(stata_cmd, timevar, panelvar, tdelta)
      timevar  = hints$timevar
      panelvar = hints$panelvar
      tdelta   = hints$tdelta

      # Optionally emit R code to document the TS state change
      r_df$r_code[i] = paste0("# TS State Updated: panelvar=", panelvar,
                              ", timevar=", timevar, ", tdelta=", tdelta)
      next
    }

    # 2. Replace TS operators in the translated R code
    rc = r_df$r_code[i]
    if (!is.null(rc) && !is.na(rc) && rc != "") {
      rc = s2r_replace_ts_in_string(rc, timevar, panelvar, tdelta)
      r_df$r_code[i] = rc
    }
  }

  r_df
}

#' Parse xtset and tsset commands to extract panel and time variables
s2r_parse_xtset = function(cmd, timevar, panelvar, tdelta) {
  is_ts = grepl("^tsset\\b", cmd, ignore.case = TRUE)
  cmd_body = sub("^(xtset|tsset)\\s+", "", cmd, ignore.case = TRUE)

  # Extract delta(...) if present
  delta_match = stringi::stri_match_first_regex(cmd_body, "delta\\(([^)]+)\\)")
  if (!is.na(delta_match[1,1])) {
    tdelta = as.numeric(delta_match[1,2])
  }
  cmd_body = sub(",.*", "", cmd_body) # Strip options

  vars = strsplit(trimws(cmd_body), "\\s+")[[1]]
  vars = vars[vars != ""]

  if (length(vars) >= 2) {
    panelvar = vars[1]
    timevar  = vars[2]
  } else if (length(vars) == 1) {
    if (is_ts) {
      timevar  = vars[1]
      panelvar = NA_character_
    } else {
      # Stata allows 'xtset panelvar' without a time variable
      panelvar = vars[1]
      timevar  = NA_character_
    }
  }

  list(timevar = timevar, panelvar = panelvar, tdelta = tdelta)
}

#' Find TS operators (like d.x1) and replace with collapse calls
s2r_replace_ts_in_string = function(rc, timevar, panelvar, tdelta) {
  rx = "\\b([LlFfDdSsOo])([0-9]*)\\.([a-zA-Z0-9_]+)\\b"
  matches = stringi::stri_match_all_regex(rc, rx)[[1]]

  if (is.na(matches[1,1])) return(rc)

  for (i in seq_len(nrow(matches))) {
    full_match = matches[i, 1]
    op_type    = toupper(matches[i, 2])
    op_num     = matches[i, 3]
    op_num     = ifelse(op_num == "", 1, as.integer(op_num))
    base_var   = matches[i, 4]

    # Construct collapse call
    args = c(paste0("x = ", base_var))

    n_val = op_num
    diff_val = 1
    tdelta_val = if (!is.null(tdelta) && !is.na(tdelta)) as.numeric(tdelta) else 1

    if (op_type == "L") {
      fun = "sfun_flag"
      n_val = op_num
    } else if (op_type == "F") {
      fun = "sfun_flag"
      n_val = -op_num
    } else if (op_type == "D") {
      fun = "sfun_fdiff"
      diff_val = op_num
      n_val = 1
    } else if (op_type == "S") {
      fun = "sfun_fdiff"
      n_val = op_num
    } else if (op_type == "O") {
      # O. means omitted. Just fallback to the base variable
      # We strip backticks if they were added
      rc = gsub(paste0("`", full_match, "`"), base_var, rc, fixed = TRUE)
      rc = gsub(full_match, base_var, rc, fixed = TRUE)
      next
    }

    if (tdelta_val > 1 && op_type %in% c("L","F","D","S")) {
      n_val = n_val * tdelta_val
    }

    if (op_type %in% c("L", "F", "S")) {
      args = c(args, paste0("n = ", n_val))
    } else if (op_type == "D") {
      args = c(args, paste0("diff = ", diff_val))
      if (tdelta_val > 1) args = c(args, paste0("n = ", n_val))
    }

    if (!is.null(timevar) && !is.na(timevar) && timevar != "") {
      args = c(args, paste0("t = ", timevar))
    }
    if (!is.null(panelvar) && !is.na(panelvar) && panelvar != "") {
      args = c(args, paste0("g = ", panelvar))
    }

    r_expr = paste0(fun, "(", paste0(args, collapse = ", "), ")")

    # stata2r wraps variables with dots in backticks (e.g. `d.x1`).
    # We must replace the backticked version first, then the bare version.
    rc = gsub(paste0("`", full_match, "`"), r_expr, rc, fixed = TRUE)
    rc = gsub(full_match, r_expr, rc, fixed = TRUE)
  }

  rc
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/s2r_ts_op.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_compress_col_type.R
```
# Custom R implementation for Stata's compress logic for numeric types.
# Attempts to convert numeric vectors to integer if all non-NA values are integers
# and within the range of R's integer type.

sfun_compress_col_type = function(x) {
  restore.point("sfun_compress_col_type")
  if (is.numeric(x)) {
    # Check if all non-NA values are integers and within R's integer range
    # Also check if there are any non-NA values to avoid issues with empty vectors or all NAs
    if (length(x[!is.na(x)]) > 0 && all(x == floor(x), na.rm = TRUE) && all(x >= -.Machine$integer.max & x <= .Machine$integer.max, na.rm = TRUE)) {
      return(as.integer(x))
    }
  }
  return(x)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_compress_col_type.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_date_utils.R
```
# Custom R implementation for utility functions related to Stata date formats.

is_stata_fmt_allowing_2_digit_year = function(fmt) {
  # Stata formats that allow 2-digit years (YY) implicitly or explicitly.
  # This function checks for common daily date formats where Stata's `date()`
  # function might apply century logic even if the input string contains a 4-digit year.
  # These are the formats that typically have a 'Y' or 'y' component for the year.
  tolower(fmt) %in% c("ymd", "mdy", "dmy", "dy", "my", "yd", "yw", "wq", "wm", "wd")
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_date_utils.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_day.R
```
# Custom R implementation for Stata's day() behavior
# Stata: day(date_value) returns the day of the month (1-31) of a Stata date value.

sfun_day = function(stata_date_values) {
  restore.point("sfun_day")
  # Convert Stata date (numeric days since 1960-01-01) to R Date object.
  # as.Date handles NA values correctly.
  r_dates = as.Date(stata_date_values, origin = "1960-01-01")
  
  # Extract day as numeric.
  # format() returns a character string, so convert to numeric.
  # This will result in NA for any invalid date conversions.
  return(as.numeric(format(r_dates, "%d")))
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_day.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_dow.R
```
# Custom R implementation for Stata's dow() behavior
# Stata: dow(date_value) returns the day of the week (0-6) of a Stata date value.
# 0 = Sunday, 1 = Monday, ..., 6 = Saturday.

sfun_dow = function(stata_date_values) {
  restore.point("sfun_dow")
  # Convert Stata date (numeric days since 1960-01-01) to R Date object.
  # as.Date handles NA values correctly.
  r_dates = as.Date(stata_date_values, origin = "1960-01-01")
  
  # Extract day of the week as numeric (0 for Sunday, ..., 6 for Saturday).
  # format() with "%w" provides this behavior.
  # This will result in NA for any invalid date conversions.
  return(as.numeric(format(r_dates, "%w")))
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_dow.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_is_stata_expression_string_typed.R
```
sfun_is_stata_expression_string_typed = function(stata_expr_original) {
  restore.point("sfun_is_stata_expression_string_typed")
  
  # Ensure stata_expr_original is a single character string or NA
  if (is.null(stata_expr_original) || length(stata_expr_original) == 0 || !is.character(stata_expr_original)) {
      stata_expr_original = NA_character_
  } else {
      stata_expr_original = as.character(stata_expr_original[1])
  }

  if (is.na(stata_expr_original) || stata_expr_original == "") return(FALSE)

  # NEW: 1. Check for logical/comparison operators. If present, the result is numeric (0/1).
  # This must precede the string literal check.
  if (dplyr::coalesce(stringi::stri_detect_regex(stata_expr_original, "==|!=|<=|>=|<|>|&|\\|"), FALSE)) {
    return(FALSE)
  }

  # 2. `cond(condition, val_if_true, val_if_false)`: if any value (val_if_true, val_if_false) is string, result is string.
  #    This check must come BEFORE generic string literal check.
  cond_match = stringi::stri_match_first_regex(stata_expr_original, "\\bcond\\(([^,]+),([^,]+),([^)]+)\\)")
  if (!is.na(cond_match[1,1])) {
      val_if_true_str = stringi::stri_trim_both(cond_match[1,3])
      val_if_false_str = stringi::stri_trim_both(cond_match[1,4])
      # Recursively check the arguments for string type
      if (dplyr::coalesce(sfun_is_stata_expression_string_typed(val_if_true_str), FALSE) ||
          dplyr::coalesce(sfun_is_stata_expression_string_typed(val_if_false_str), FALSE)) {
          return(TRUE)
      } else {
          # If both are numeric, cond is numeric
          return(FALSE)
      }
  }

  # 3. Check for explicitly numeric-returning functions. If found, return FALSE immediately.
  numeric_producing_functions = c(
    "log", "sqrt", "int", "round", "mod", "runiform", "mdy", "date",
    "year", "month", "day", "qofd", "dow", "missing",
    # Stata type casting functions that convert to numeric:
    "float", "double", "long", "int", "byte"
  )
  for (func in numeric_producing_functions) {
    if (dplyr::coalesce(stringi::stri_detect_regex(stata_expr_original, paste0("\\b", func, "\\s*\\(")), FALSE)) {
      return(FALSE)
    }
  }

  # 4. Check for explicitly string-returning functions.
  string_producing_functions = c(
    "char", "itrim", "lower", "ltrim", "proper", "rtrim", "string", "subinstr",
    "substr", "strl", "strpos", "strreverse", "strtrim", "trim", "upper",
    "ustrleft", "ustrlower", "ustrpos", "ustrright", "ustrtrim", "ustrunescape",
    "ustrupper", "ustrword", "ustrwordcount", "word", "wordcount",
    # Stata type casting functions that convert to string:
    "string"
  )
  for (func in string_producing_functions) {
    if (dplyr::coalesce(stringi::stri_detect_regex(stata_expr_original, paste0("\\b", func, "\\s*\\(")), FALSE)) {
      return(TRUE)
    }
  }
  
  # NEW: 5. Check for '+' operator and string literals.
  #    If expression contains '+' AND a string literal, it's likely string concatenation.
  #    This check is a heuristic.
  if (dplyr::coalesce(stringi::stri_detect_fixed(stata_expr_original, "+"), FALSE) &&
      dplyr::coalesce(stringi::stri_detect_regex(stata_expr_original, '"[^"]*"|\'[^\']*\'' ), FALSE)) {
      return(TRUE)
  }

  # 6. Contains any string literal (text enclosed in double or single quotes)
  #    This must come after function/operator checks.
  if (dplyr::coalesce(stringi::stri_detect_regex(stata_expr_original, '"[^"]*"|\'[^\']*\'' ), FALSE)) {
    return(TRUE)
  }

  # If none of the above rules apply, default to numeric.
  # This implies that if it's a variable reference, it's numeric unless explicitly string.
  # Or if it's a simple arithmetic expression, it's numeric.
  return(FALSE)
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_is_stata_expression_string_typed.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_missing.R
```
# Custom R implementation of Stata function missing

# Stata's missing() function checks for system missing (.) and extended missing values (.a to .z).
# In R, these are typically all read as NA by packages like `haven`.
# Additionally, for string variables, Stata's missing() treats empty strings ("") or strings containing only blanks as missing.
sfun_missing = function(x) {
  restore.point("sfun_missing")
  if (is.numeric(x)) {
    return(is.na(x))
  } else if (is.character(x)) {
    # For character vectors, consider NA or empty/blank strings as missing
    return(is.na(x) | stringi::stri_trim_both(x) == "")
  }
  return(is.na(x)) # Default for other types
}

# Example usage if you wanted to call this explicitly:
# data = data %>% dplyr::mutate(new_var = sfun_missing(old_var))
# However, direct translation to is.na() is preferred in generated code for simplicity.

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_missing.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_month.R
```
# Custom R implementation for Stata's month() behavior
# Stata: month(date_value) returns the month (1-12) of a Stata date value.

sfun_month = function(stata_date_values) {
  restore.point("sfun_month")
  # Convert Stata date (numeric days since 1960-01-01) to R Date object.
  # as.Date handles NA values correctly.
  r_dates = as.Date(stata_date_values, origin = "1960-01-01")
  
  # Extract month as numeric.
  # format() returns a character string, so convert to numeric.
  # This will result in NA for any invalid date conversions.
  return(as.numeric(format(r_dates, "%m")))
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_month.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_normalize_string_nas.R
```
# Custom R implementation to normalize string NAs to empty strings ""
# This is to match Stata's behavior where missing string values are empty strings.

sfun_normalize_string_nas = function(df) {
  restore.point("sfun_normalize_string_nas")
  # Iterate over columns and apply conversion for character columns
  for (col_name in names(df)) {
    if (is.character(df[[col_name]])) {
      # Use base R for assignment to ensure robustness
      df[[col_name]][is.na(df[[col_name]])] = ""
    }
  }
  return(df)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_normalize_string_nas.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_qofd.R
```
# Custom R implementation for Stata's qofd() behavior
# Stata: qofd(date_value) returns the quarter of the year (1-4) of a Stata date value.
#
# Note: The provided test data for `obs_quarter` (`do2` test case) appeared to be
# Stata's 0-indexed quarterly date values (quarters since 1960q1, where 1960q1 is 0).
# This implementation has been corrected to strictly return the quarter of the year (1-4)
# as per Stata's `qofd()` function, which expects a daily date and returns its quarter.

sfun_qofd = function(stata_date_values) {
  restore.point("sfun_qofd")
  # Convert Stata date (numeric days since 1960-01-01) to R Date object.
  # as.Date handles NA values correctly.
  r_dates = as.Date(stata_date_values, origin = "1960-01-01")

  # Extract month from the R Date object
  months = as.numeric(format(r_dates, "%m"))

  # Calculate quarter of the year (1-4) based on month
  quarters_of_year = ceiling(months / 3)

  # Ensure NA for invalid dates (if r_dates was NA, result should be NA)
  quarters_of_year[is.na(r_dates)] = NA_real_

  return(quarters_of_year)
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_qofd.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_add.R
```
# Custom R implementation for Stata's polymorphic '+' operator.
# Stata's '+' operator performs numeric addition if both operands are numeric.
# If one or both operands are strings, it performs string concatenation (after converting numeric operands to string).
# Stata's missing value handling for '+' is specific:
# numeric + numeric: standard addition, NA if any operand is NA.
# string + string: concatenation.
# numeric + string: numeric converted to string, then concatenation.
# . (missing numeric) + string: . converted to "" for concatenation. Result is string.
# string + . (missing numeric): . converted to "" for concatenation. Result is string.
# . (missing numeric) + . (missing numeric): . Result is NA (numeric).

sfun_stata_add = function(x, y) {
  restore.point("sfun_stata_add")
  # If both are numeric, perform numeric addition.
  # This correctly handles NA + NA = NA, numeric + NA = NA.
  if (is.numeric(x) && is.numeric(y)) {
    return(x + y)
  } else {
    # If not both numeric, assume string concatenation.
    # Convert both to character.
    x_char = as.character(x)
    y_char = as.character(y)

    # Stata specific: missing numeric (NA in R) and string missing (NA_character_ in R)
    # become empty string for concatenation.
    x_val = x_char
    y_val = y_char
    x_val[is.na(x_val)] = ""
    y_val[is.na(y_val)] = ""

    return(paste0(x_val, y_val))
  }
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_add.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_cond.R
```
# Custom R implementation for Stata's cond() function.
# Stata: cond(x, a, b) returns a if x is true (non-zero and non-missing), otherwise returns b.

sfun_stata_cond = function(condition_val, true_val, false_val) {
  restore.point("sfun_stata_cond")
  # Convert condition_val to numeric. NAs in original numeric_cond will propagate.
  numeric_cond = as.numeric(condition_val)
  
  # The condition for 'true' in Stata's cond() is: not missing AND not zero.
  # This correctly handles Stata's missing values (e.g., .) and 0 as 'false'.
  is_true_in_stata = !is.na(numeric_cond) & numeric_cond != 0
  
  # Determine target type based on true_val and false_val
  # Stata's cond() type promotion: string > numeric (float > long > int > byte)
  # If either is string, result is string.
  # If both are numeric, result is numeric (float if any float, else integer).
  if (is.character(true_val) || is.character(false_val)) {
    true_val_coerced = as.character(true_val)
    false_val_coerced = as.character(false_val)
    # Stata's cond() converts numeric missing to "" if result is string.
    true_val_coerced[is.na(true_val_coerced)] = ""
    false_val_coerced[is.na(false_val_coerced)] = ""
    return(dplyr::if_else(is_true_in_stata, true_val_coerced, false_val_coerced))
  } else {
    # If not character, both are numeric or convertible to numeric.
    # To avoid integer/double mismatch with NA_real_ (which is double),
    # ensure both `true_val` and `false_val` are converted to the most general numeric type (double)
    # before `if_else`. The final casting to integer/double will be handled in t_generate/t_replace
    # based on Stata's type rules for the target variable.
    return(dplyr::if_else(is_true_in_stata, as.numeric(true_val), as.numeric(false_val)))
  }
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_cond.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_date.R
```
sfun_stata_date = function(s, fmt, century_pivot = NULL) {
  restore.point("sfun_stata_date")

  # Apply sfun_stata_date_single to each element of s
  # vapply ensures the output type is numeric(1) for each element,
  # and the result is a numeric vector.
  vapply(s, sfun_stata_date_single, FUN.VALUE = numeric(1), fmt = fmt, century_pivot = century_pivot)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_date.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_date_single.R
```
# Helper function for sfun_stata_date (non-vectorized core logic)
sfun_stata_date_single = function(s, fmt, century_pivot = NULL) {
  restore.point("sfun_stata_date_single")

  # Handle NA input
  if (is.na(s)) return(NA_real_)

  # Stata's default century for date() is 2000 if not specified (e.g., date("1/1/60", "MDY") -> 2060)
  # The 'century_pivot' argument shifts this.
  actual_century_pivot = if (is.null(century_pivot)) 2000 else as.numeric(century_pivot)

  # Define common R format strings based on Stata's fmt, including variants with/without separators and 2/4 digit years
  r_formats = switch(tolower(fmt),
    "ymd" = c("%Y%m%d", "%Y-%m-%d", "%Y/%m/%d", "%y%m%d", "%y-%m-%d", "%y/%m/%d"),
    "mdy" = c("%m%d%Y", "%m-%d-%Y", "%m/%d/%Y", "%m%d%y", "%m-%d-%y", "%m/%d/%y"),
    "dmy" = c("%d%m%Y", "%d-%m-%Y", "%d/%m/%Y", "%d%m%y", "%d-%m-%y", "%d/%m/%y"),
    stop("sfun_stata_date_single: Unsupported date format '", fmt, "'")
  )

  parsed_date = as.Date(NA_character_)
  format_used = NA_character_

  # Try parsing with multiple formats until successful
  for (f in r_formats) {
    temp_date = suppressWarnings(as.Date(s, format = f))
    if (!is.na(temp_date)) {
      parsed_date = temp_date
      format_used = f
      break
    }
  }

  # If parsing failed, return NA
  if (is.na(parsed_date)) {
    return(NA_real_)
  }

  # Apply Stata's century pivot logic for two-digit years if the format *type* allows it.
  # This is a more robust check than just `grepl("%y", format_used)` as Stata's `date()`
  # function applies this logic based on the format's capacity for 2-digit years,
  # even if a 4-digit year is provided in the input string.
  if (is_stata_fmt_allowing_2_digit_year(fmt)) {
    current_year_full = as.numeric(format(parsed_date, "%Y"))
    current_year_two_digits = current_year_full %% 100
    
    pivot_year_last_two_digits = actual_century_pivot %% 100
    
    if (current_year_two_digits >= pivot_year_last_two_digits) {
      # If two-digit year is >= pivot_year_last_two_digits, it belongs to the previous century (e.g., 19xx for 2050 pivot)
      corrected_year = floor(actual_century_pivot / 100) * 100 - 100 + current_year_two_digits
    } else {
      # If two-digit year is < pivot_year_last_two_digits, it belongs to the current century (e.g., 20xx for 2050 pivot)
      corrected_year = floor(actual_century_pivot / 100) * 100 + current_year_two_digits
    }
    
    # Reconstruct date with corrected year if needed (only if corrected_year is different)
    if (corrected_year != current_year_full) {
      parsed_date = as.Date(paste(corrected_year, format(parsed_date, "%m-%d"), sep="-"))
    }
  }

  # Return numeric value as days since 1960-01-01 (Stata's epoch)
  # Stata's `date()` and `mdy()` functions define 01jan1960 as 0.
  # R's `as.numeric(as.Date("1960-01-01") - as.Date("1960-01-01"))` correctly yields 0.
  stata_date = as.numeric(parsed_date - as.Date("1960-01-01"))

  return(stata_date)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_date_single.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_mdy.R
```
# Custom R implementation for Stata's mdy() behavior
# Stata: mdy(M,D,Y) returns the number of days since 01jan1960.

sfun_stata_mdy = function(M, D, Y) {
  restore.point("sfun_stata_mdy")
  # Create a string in "YYYY-MM-DD" format that as.Date can parse
  date_str = paste0(Y, "-", sprintf("%02d", M), "-", sprintf("%02d", D))
  
  # Convert to R Date object. Suppress warnings for invalid dates (e.g., Feb 30).
  # Invalid dates will result in NA.
  r_date = suppressWarnings(as.Date(date_str, format = "%Y-%m-%d"))
  
  # Return numeric value as days since 1960-01-01 (Stata's epoch)
  # Stata's `date()` and `mdy()` functions define 01jan1960 as 0.
  # R's `as.numeric(as.Date("1960-01-01") - as.Date("1960-01-01"))` correctly yields 0.
  stata_date_value = as.numeric(r_date - as.Date("1960-01-01"))
  
  return(stata_date_value)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_mdy.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_round.R
```
# Custom R implementation for Stata's round() behavior
# Stata: round(x) is equivalent to round(x,1)
# Stata: round(x,y) rounds x to the nearest multiple of y.
# For .5 cases, Stata rounds away from zero. (e.g. round(2.5,1)=3, round(-2.5,1)=-3)

sfun_stata_round = function(x, unit = 1) {
  # Ensure unit is positive, Stata's unit is always > 0
  if (any(unit <= 0, na.rm = TRUE)) {
    stop("sfun_stata_round: rounding unit must be positive.")
  }
  # Standard R NA handling: if x or unit is NA, result is NA
  # Using vectorized ifelse for NA handling implicitly
  return(ifelse(is.na(x) | is.na(unit), NA, sign(x) * floor(abs(x)/unit + 0.5) * unit))
}

# Example Usage:
# sfun_stata_round(2.5)    # Expected: 3
# sfun_stata_round(-2.5)   # Expected: -3
# sfun_stata_round(2.34, 0.1) # Expected: 2.3
# sfun_stata_round(2.35, 0.1) # Expected: 2.4
# sfun_stata_round(c(2.5, -2.5, NA, 5.25), 0.5) # Expected: c(2.5, -2.5, NA, 5.5) # Stata: round(5.25, .5) is 5.5. My formula: sign(5.25)*floor(abs(5.25)/.5 + .5)*.5 = 1*floor(10.5+0.5)*.5 = 1*11*.5 = 5.5

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stata_round.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_string.R
```
# Custom R implementation for Stata's string() behavior
# Stata: string(x) converts numeric x to string.
# Missing numeric values (.) are converted to an empty string ("").

sfun_string = function(x) {
  restore.point("sfun_string")
  
  # Initialize result vector of character type
  res = character(length(x))
  
  # Handle non-missing values: convert them to character
  # This correctly converts numeric values to their string representation.
  res[!is.na(x)] = as.character(x[!is.na(x)])
  
  # Handle missing values (NA in R): convert them to an empty string ("")
  # This directly addresses the Stata `.` to `""` conversion rule.
  res[is.na(x)] = ""
  
  return(res)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_string.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_strip_stata_attributes.R
```
sfun_strip_stata_attributes = function(x) {
  restore.point("sfun_strip_stata_attributes")
  # For data frames, apply to each column. For vectors, strip attributes directly.
  if (is.data.frame(x)) {
    # Apply recursively to each column, ensuring it stays a data.frame/tibble
    x[] = lapply(x, sfun_strip_stata_attributes)
    return(x)
  } else {
    # Handle individual vectors (columns)
    if (inherits(x, "haven_labelled")) {
      # Convert haven_labelled to its underlying base type (numeric, character, or factor if labels imply factors)
      x = haven::zap_labels(x)
      x = haven::zap_formats(x)
      x = haven::zap_missing(x)
    }
    
    # Preserve Date class, just strip other attributes.
    # This must come before is.numeric(x) check as Date objects are also numeric.
    if (inherits(x, "Date")) {
      attr_names_to_remove = setdiff(names(attributes(x)), c("names", "class")) # Keep class for Date
      if (length(attr_names_to_remove) > 0) {
        attributes(x)[attr_names_to_remove] = NULL
      }
      return(x)
    }
    
    # Explicitly cast to base R types to ensure no problematic attributes remain
    # This also handles cases where a variable might have been an R factor or other
    # specific class that Stata doesn't have a direct equivalent for.
    if (is.numeric(x)) {
      # Removed explicit rounding. Let `compare_df`'s tolerance handle precision differences.
      x = as.numeric(x)
    } else if (is.character(x)) {
      x = as.character(x)
    } else if (is.logical(x)) {
      x = as.logical(x)
    } else if (is.factor(x)) {
      # Convert factors to character for consistency with Stata strings.
      # Stata doesn't have factors, string conversion is the closest equivalent.
      x = as.character(x)
    }
    # For any other generic attributes, remove them, but keep 'names'.
    attr_names_to_remove = setdiff(names(attributes(x)), "names")
    if (length(attr_names_to_remove) > 0) {
      attributes(x)[attr_names_to_remove] = NULL
    }
    return(x)
  }
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_strip_stata_attributes.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_stritrim.R
```
# Custom R implementation for Stata's stritrim() behavior
# Stata: stritrim(s) removes leading/trailing spaces and replaces multiple internal spaces with one.

sfun_stritrim = function(s) {
  restore.point("sfun_stritrim")
  # Remove leading/trailing spaces
  s = stringi::stri_trim_both(s)
  # Replace multiple internal spaces with a single space
  s = stringi::stri_replace_all_regex(s, "\\s+", " ")
  return(s)
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_stritrim.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_strpos.R
```
# Custom R implementation for Stata's strpos() behavior
# Stata: strpos(haystack, needle) returns the first position of needle in haystack.
# Returns 0 if needle is not found.

sfun_strpos = function(haystack, needle) {
  restore.point("sfun_strpos")
  # stringi::stri_locate_first_fixed returns a matrix [start, end]
  # or [NA, NA] if not found. We need the start position.
  loc = stringi::stri_locate_first_fixed(haystack, needle)
  start_pos = loc[,1]
  return(ifelse(is.na(start_pos), 0L, as.integer(start_pos)))
}

# Example Usage:
# sfun_strpos("this is a test", "is")  # Expected: 3
# sfun_strpos("this is a test", "not") # Expected: 0
# sfun_strpos(c("apple", "banana", "apricot"), "ap") # Expected: c(1, 0, 1)

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_strpos.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_subinstr.R
```
# Custom R implementation for Stata's subinstr() behavior
# Stata: subinstr(s1, s2, s3, n) replaces n occurrences of s2 with s3 in s1.
# If n is 0 or negative, or if n is ., all occurrences are replaced.
# If s2 is "", s1 is returned.

sfun_subinstr = function(s1, s2, s3, n) {
  restore.point("sfun_subinstr")
  # Handle s2 being empty string
  if (is.character(s2) && s2 == "") {
    return(s1)
  }

  # Stata's `.` for `n` is NA in R. Non-positive `n` also means all.
  if (is.na(n) || n <= 0) {
    # Replace all occurrences
    return(stringi::stri_replace_all_fixed(s1, s2, s3))
  } else if (n == 1) {
    # Replace first occurrence
    return(stringi::stri_replace_first_fixed(s1, s2, s3))
  } else {
    # For n > 1 and finite, Stata replaces only n times.
    # stringi::stri_replace_all_fixed doesn't have a 'limit' argument.
    # This is a known limitation for perfect emulation for n > 1 and finite.
    # For now, if n > 1 and finite, we will replace all.
    warning("sfun_subinstr: Stata's subinstr with finite n > 1 is not perfectly emulated. All occurrences will be replaced.")
    return(stringi::stri_replace_all_fixed(s1, s2, s3))
  }
}

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_subinstr.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_ts_utils.R
```

#' Safe wrapper for collapse::flag explicitly checking vector length
sfun_flag = function(x, n = 1, ...) {
  if (length(x) <= abs(n)) return(rep(NA_real_, length(x)))
  collapse::flag(x, n = n, ...)
}

#' Safe wrapper for collapse::fdiff explicitly checking vector length constraint
sfun_fdiff = function(x, n = 1, diff = 1, ...) {
  if (length(x) <= abs(n * diff)) return(rep(NA_real_, length(x)))
  collapse::fdiff(x, n = n, diff = diff, ...)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_ts_utils.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/sfun_year.R
```
# Custom R implementation for Stata's year() behavior
# Stata: year(date_value) returns the year of a Stata date value.

sfun_year = function(stata_date_values) {
  restore.point("sfun_year")
  # Convert Stata date (numeric days since 1960-01-01) to R Date object.
  # as.Date handles NA values correctly.
  r_dates = as.Date(stata_date_values, origin = "1960-01-01")

  # Extract year as numeric.
  # format() returns a character string, so convert to numeric.
  # This will result in NA for any invalid date conversions.
  return(as.numeric(format(r_dates, "%Y")))
}


```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/sfun_year.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/stata2r_globals.R
```
# Global environment to store package-wide settings, e.g., data directory
stata2r_env = new.env(parent=globalenv())

```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/stata2r_globals.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/stata_cmd_utils.R
```
# Stata command utilities

# Main Stata commands and their abbreviations
# This list is not exhaustive but covers many common commands.
stata_cmd_abbreviations = list(
  "a" = "append",
  "br" = "browse",
  "by" = "bysort",
  "cap" = "capture",
  "cd" = "cd",
  "cl" = "clear",
  "co" = "collapse",
  "comp" = "compress",
  "conf" = "confirm",
  "cons" = "constraint",
  "contr" = "contrast",
  "cop" = "copy",
  "cor" = "correlate",
  "cou" = "count",
  "d" = "describe",
  "de" = "decode",
  "dest" = "destring",
  "di" = "display",
  "dir" = "dir",
  "do" = "do",
  "dr" = "drop",
  "du" = "duplicates",
  "e" = "edit",
  "eg" = "egen",
  "en" = "encode",
  "er" = "erase",
  "est" = "estimates",
  "ex" = "expand",
  "f" = "fillin",
  "g" = "generate",
  "gr" = "graph",
  "gs" = "gsort",
  "h" = "help",
  "i" = "inspect",
  "ins" = "insheet",
  "k" = "keep",
  "l" = "list",
  "la" = "label",
  "logi" = "logit",
  "m" = "merge",
  "mark" = "marksample",
  "markout" = "markout",
  "mat" = "matrix",
  "mem" = "memory",
  "mkdir" = "mkdir",
  "mo" = "more",
  "mov" = "move",
  "mv" = "mvdecode",
  "n" = "notes",
  "o" = "order",
  "ou" = "outsheet",
  "p" = "predict",
  "pres" = "preserve",
  "q" = "quietly",
  "r" = "recode",
  "reg" = "regress",
  "ren" = "rename",
  "res" = "reshape",
  "rest" = "restore",
  "ret" = "return",
  "rm" = "rmdir",
  "ru" = "run",
  "sa" = "save",
  "sc" = "scalar",
  "se" = "set",
  "sh" = "shell",
  "sig" = "signestim",
  "so" = "sort",
  "st" = "stata",
  "su" = "summarize",
  "sy" = "sysuse",
  "t" = "tabulate",
  "te" = "test",
  "temp" = "tempfile",
  "ty" = "type",
  "u" = "use",
  "v" = "version",
  "w" = "which",
  "xi" = "xi"
)


# Function to get the full Stata command name from a token (could be an abbreviation)
get_stata_full_cmd_name = function(cmd_token) {
  restore.point("get_stata_full_cmd_name")
  if (is.na(cmd_token) || cmd_token == "") {
    return(NA_character_)
  }
  cmd_token_lower = tolower(cmd_token)
  if (isTRUE(cmd_token_lower %in% names(stata_cmd_abbreviations))) {
    return(stata_cmd_abbreviations[[cmd_token_lower]])
  }

  # Check if it matches a prefix of a known full command,
  # AND is longer than the minimum abbreviation
  for (abbr in names(stata_cmd_abbreviations)) {
    full_cmd = stata_cmd_abbreviations[[abbr]]
    if (startsWith(full_cmd, cmd_token_lower) && startsWith(cmd_token_lower, abbr)) {
      return(full_cmd)
    }
  }

  return(cmd_token_lower)
}

# Vectorized version of get_stata_full_cmd_name
get_stata_full_cmd_name_vec = function(cmd_tokens) {
  restore.point("get_stata_full_cmd_name_vec")

  res = rep(NA_character_, length(cmd_tokens))
  valid_idx = !is.na(cmd_tokens) & cmd_tokens != ""

  if (any(valid_idx)) {
    cmd_tokens_lower = tolower(cmd_tokens[valid_idx])
    res_valid = cmd_tokens_lower

    abbrs = names(stata_cmd_abbreviations)
    full_cmds = unlist(stata_cmd_abbreviations, use.names = FALSE)

    # 1. Exact match in abbreviations
    exact_match = match(cmd_tokens_lower, abbrs)
    has_exact = !is.na(exact_match)
    res_valid[has_exact] = full_cmds[exact_match[has_exact]]

    # 2. Prefix matching for those without exact match
    needs_prefix = !has_exact
    if (any(needs_prefix)) {
      tokens_to_check = cmd_tokens_lower[needs_prefix]
      resolved = tokens_to_check

      for (i in seq_along(tokens_to_check)) {
        tok = tokens_to_check[i]
        for (j in seq_along(abbrs)) {
          abbr = abbrs[j]
          full_cmd = full_cmds[j]
          if (startsWith(full_cmd, tok) && startsWith(tok, abbr)) {
            resolved[i] = full_cmd
            break
          }
        }
      }
      res_valid[needs_prefix] = resolved
    }
    res[valid_idx] = res_valid
  }
  return(res)
}


# List of Stata commands considered to modify the dataset
stata_data_manip_cmds = c(
  "append", "collapse", "compress", "contract", "decode", "destring", "drop",
  "duplicates", "egen", "encode", "expand", "fillin",
  "generate", "gen", "gsort", "input", "insheet", "keep", "label",
  "merge", "modify", "move", "mvdecode", "mvrecode", "order", "pctile",
  "predict",
  "preserve", "recode", "rename", "reshape", "restore", "sample", "save", "set",
  "sort", "stack", "statsby", "stsplit",
  "svar", "sysuse",
  "tempfile", "tempvar", "tempname",
  "total",
  "use", "xtile", "xi",
  "replace", "clear", "scalar", "sc"
)

# Commands that primarily display info or control program flow, and never
# modify data or produce e()/r() results for later use.
stata_non_data_manip_cmds = c(
  "assert", "browse", "capture", "cd", "confirm", "constraint", "display", "di", "do", "edit", "erase", "error",
  "exit", "findit", "format", "graph", "gr", "help", "h", "if", "inspect", "i", "list", "l", "log", "lookup", "marksample",
  "matrix", "mat", "memory", "mem", "mkdir", "more", "mo", "notes", "n", "outfile", "outsheet", "ou", "pause", "plot",
  "print", "program", "pwd", "query",
  "return", "ret", "rmdir", "run", "ru", "search", "shell", "sh", "signestim", "sleep",
  "stata", "st", "tabdisp", "table", "test", "te", "timer", "translate", "truncate",
  "tutorials", "type", "ty", "view", "version", "v", "webuse", "w", "which", "while", "window", "winexec", "xmlsav"
)

# List of estimation commands that can produce e() results
stata_estimation_cmds = c(
  "regress", "logit", "probit", "ivregress", "xtreg", "areg", "reghdfe", "sem", "asmixlogit", "gmm"
)

# List of commands that can produce r() results
stata_r_result_cmds = c(
  "summarize", "su", "tabulate", "tab", "count", "correlate"
)


# Vectorized helper to parse multiple Stata command lines
parse_stata_command_lines = function(lines_text) {
  restore.point("parse_stata_command_lines")
  n = length(lines_text)
  if (n == 0) {
    return(list(
      stata_cmd_original = character(0),
      stata_cmd = character(0),
      rest_of_cmd = character(0),
      is_by_prefix = logical(0),
      is_bysort_prefix = logical(0),
      by_group_vars = character(0),
      by_sort_vars = character(0),
      is_quietly_prefix = logical(0),
      is_capture_prefix = logical(0),
      is_xi_prefix = logical(0)
    ))
  }

  effective_line = stringi::stri_trim_both(lines_text)

  is_by_prefix_val = rep(FALSE, n)
  is_bysort_prefix_val = rep(FALSE, n)
  by_group_vars = rep("", n)
  by_sort_vars = rep("", n)
  is_quietly_prefix_val = rep(FALSE, n)
  is_capture_prefix_val = rep(FALSE, n)
  is_xi_prefix_val = rep(FALSE, n)

  # 1. capture prefix
  capture_match = stringi::stri_match_first_regex(effective_line, "^(?:capture|cap)\\s+(.*)$")
  idx_cap = !is.na(capture_match[,1])
  if (any(idx_cap)) {
    is_capture_prefix_val[idx_cap] = TRUE
    effective_line[idx_cap] = stringi::stri_trim_both(capture_match[idx_cap, 2])
  }

  # 2. quietly prefix
  quietly_match = stringi::stri_match_first_regex(effective_line, "^(?:quietly|qui|q)\\s+(.*)$")
  idx_qui = !is.na(quietly_match[,1])
  if (any(idx_qui)) {
    is_quietly_prefix_val[idx_qui] = TRUE
    effective_line[idx_qui] = stringi::stri_trim_both(quietly_match[idx_qui, 2])
  }

  # 3. by / bysort prefix
  idx_by_starts = stringi::stri_startswith_fixed(effective_line, "by ") | stringi::stri_startswith_fixed(effective_line, "bysort ")
  if (any(idx_by_starts)) {
    prefix_match = stringi::stri_match_first_regex(effective_line[idx_by_starts], "^(by|bysort)\\s+([^:]+?)\\s*:\\s*(.*)$")
    valid_by = !is.na(prefix_match[,1])
    if (any(valid_by)) {
      idx_valid_by = which(idx_by_starts)[valid_by]
      raw_prefix = stringi::stri_trim_both(prefix_match[valid_by, 2])
      raw_by_string_from_prefix = stringi::stri_trim_both(prefix_match[valid_by, 3])
      effective_line[idx_valid_by] = stringi::stri_trim_both(prefix_match[valid_by, 4])

      is_by_prefix_val[idx_valid_by] = TRUE
      is_bysort_prefix_val[idx_valid_by] = (raw_prefix == "bysort")

      for (i in seq_along(idx_valid_by)) {
        raw_str = raw_by_string_from_prefix[i]
        grp_vars = character(0)
        srt_vars = character(0)

        if (!is.na(raw_str) && raw_str != "") {
          match_result = stringi::stri_match_all_regex(raw_str, "\\s*(\\([^)]+\\)|[^\\s()]+)\\s*")
          if (!is.null(match_result[[1]]) && NROW(match_result[[1]]) > 0) {
            by_tokens = match_result[[1]][,2]
            for (token in by_tokens) {
              if (stringi::stri_startswith_fixed(token, "(") && stringi::stri_endswith_fixed(token, ")")) {
                sort_vars_in_paren = stringi::stri_sub(token, 2, -2)
                srt_vars = c(srt_vars, stringi::stri_split_regex(stringi::stri_trim_both(sort_vars_in_paren), "\\s+")[[1]])
              } else {
                grp_vars = c(grp_vars, token)
              }
            }
          }
        }

        grp_vars = grp_vars[!is.na(grp_vars) & grp_vars != ""]
        srt_vars = srt_vars[!is.na(srt_vars) & srt_vars != ""]

        if (length(grp_vars) > 0) by_group_vars[idx_valid_by[i]] = paste(grp_vars, collapse = ",")
        if (length(srt_vars) > 0) by_sort_vars[idx_valid_by[i]] = paste(srt_vars, collapse = ",")
      }
    }
  }

  # 4. xi: prefix
  xi_match = stringi::stri_match_first_regex(effective_line, "^(?:xi)\\s*:\\s*(.*)$")
  idx_xi = !is.na(xi_match[,1])
  if (any(idx_xi)) {
    is_xi_prefix_val[idx_xi] = TRUE
    effective_line[idx_xi] = stringi::stri_trim_both(xi_match[idx_xi, 2])
  }

  # Extract command token from prefix-stripped line
  parts_mat = stringi::stri_split_fixed(effective_line, " ", n = 2, simplify = NA)

  if (is.matrix(parts_mat)) {
    cmd_token_original = stringi::stri_trim_both(parts_mat[, 1])
    rest_of_cmd = stringi::stri_trim_both(parts_mat[, 2])
  } else {
    # Fallback for empty strings (should not normally trigger if simplify = NA and n >= 1)
    cmd_token_original = stringi::stri_trim_both(parts_mat)
    rest_of_cmd = rep(NA_character_, n)
  }

  idx_empty = is.na(cmd_token_original) | cmd_token_original == ""
  if (any(idx_empty)) {
    cmd_token_original[idx_empty] = NA_character_
  }

  stata_cmd = get_stata_full_cmd_name_vec(cmd_token_original)

  idx_by_cmd = which(!is.na(stata_cmd) & (stata_cmd == "bysort" | stata_cmd == "by"))
  if (length(idx_by_cmd) > 0) {
    is_by_prefix_val[idx_by_cmd] = FALSE
    is_bysort_prefix_val[idx_by_cmd] = FALSE
    by_group_vars[idx_by_cmd] = ""
    by_sort_vars[idx_by_cmd] = ""
    stata_cmd[idx_by_cmd[stata_cmd[idx_by_cmd] == "by"]] = "bysort"
  }

  return(list(
    stata_cmd_original = cmd_token_original,
    stata_cmd = stata_cmd,
    rest_of_cmd = rest_of_cmd,
    is_by_prefix = is_by_prefix_val,
    is_bysort_prefix = is_bysort_prefix_val,
    by_group_vars = by_group_vars,
    by_sort_vars = by_sort_vars,
    is_quietly_prefix = is_quietly_prefix_val,
    is_capture_prefix = is_capture_prefix_val,
    is_xi_prefix = is_xi_prefix_val
  ))
}


# Helper to parse basic Stata command line: cmd + rest
# Handles capture, quietly, by/bysort, and xi: prefixes.
parse_stata_command_line = function(line_text) {
  restore.point("parse_stata_command_line")
  trimmed_line = stringi::stri_trim_both(line_text)

  effective_line = trimmed_line

  is_by_prefix_val = FALSE
  is_bysort_prefix_val = FALSE
  by_group_vars = character(0)
  by_sort_vars = character(0)
  is_quietly_prefix_val = FALSE
  is_capture_prefix_val = FALSE
  is_xi_prefix_val = FALSE

  # 1. capture prefix
  capture_prefix_regex = "^(?:capture|cap)\\s+(.*)$"
  capture_match = stringi::stri_match_first_regex(effective_line, capture_prefix_regex)
  if (!is.na(capture_match[1,1])) {
    first_token_before_space = stringi::stri_extract_first_words(effective_line)
    if (tolower(first_token_before_space) %in% c("capture", "cap")) {
      is_capture_prefix_val = TRUE
      effective_line = stringi::stri_trim_both(capture_match[1,2])
    }
  }

  # 2. quietly prefix
  quietly_prefix_regex = "^(?:quietly|qui|q)\\s+(.*)$"
  quietly_match = stringi::stri_match_first_regex(effective_line, quietly_prefix_regex)
  if (!is.na(quietly_match[1,1])) {
    first_token_before_space = stringi::stri_extract_first_words(effective_line)
    if (tolower(first_token_before_space) %in% c("quietly", "qui", "q")) {
      is_quietly_prefix_val = TRUE
      effective_line = stringi::stri_trim_both(quietly_match[1,2])
    }
  }

  # 3. by / bysort prefix
  if (dplyr::coalesce(stringi::stri_startswith_fixed(effective_line, "by "), FALSE) ||
      dplyr::coalesce(stringi::stri_startswith_fixed(effective_line, "bysort "), FALSE)) {
    prefix_match = stringi::stri_match_first_regex(effective_line, "^(by|bysort)\\s+([^:]+?)\\s*:\\s*(.*)$")
    if (!is.na(prefix_match[1,1])) {
      raw_prefix = stringi::stri_trim_both(prefix_match[1,2])
      raw_by_string_from_prefix = stringi::stri_trim_both(prefix_match[1,3])
      effective_line = stringi::stri_trim_both(prefix_match[1,4])
      is_by_prefix_val = TRUE
      is_bysort_prefix_val = identical(raw_prefix, "bysort")

      by_tokens = character(0)
      if (!is.na(raw_by_string_from_prefix) && raw_by_string_from_prefix != "") {
        match_result = stringi::stri_match_all_regex(raw_by_string_from_prefix, "\\s*(\\([^)]+\\)|[^\\s()]+)\\s*")
        if (!is.null(match_result[[1]]) && NROW(match_result[[1]]) > 0) {
          by_tokens = match_result[[1]][,2]
        }
      }

      for (token in by_tokens) {
        if (dplyr::coalesce(stringi::stri_startswith_fixed(token, "(") && stringi::stri_endswith_fixed(token, ")"), FALSE)) {
          sort_vars_in_paren = stringi::stri_sub(token, 2, -2)
          by_sort_vars = c(by_sort_vars, stringi::stri_split_regex(stringi::stri_trim_both(sort_vars_in_paren), "\\s+")[[1]])
        } else {
          by_group_vars = c(by_group_vars, token)
        }
      }
      by_group_vars = by_group_vars[!is.na(by_group_vars) & by_group_vars != ""]
      by_sort_vars = by_sort_vars[!is.na(by_sort_vars) & by_sort_vars != ""]
    }
  }

  # 4. xi: prefix
  xi_match = stringi::stri_match_first_regex(effective_line, "^(?:xi)\\s*:\\s*(.*)$")
  if (!is.na(xi_match[1,1])) {
    is_xi_prefix_val = TRUE
    effective_line = stringi::stri_trim_both(xi_match[1,2])
  }

  # Extract command token from prefix-stripped line
  parts = stringi::stri_split_fixed(effective_line, " ", n = 2)
  cmd_token_original = stringi::stri_trim_both(parts[[1]][1])

  if (is.na(cmd_token_original) || cmd_token_original == "") {
    return(list(
      stata_cmd_original = NA_character_,
      stata_cmd = NA_character_,
      rest_of_cmd = NA_character_,
      is_by_prefix = is_by_prefix_val,
      is_bysort_prefix = is_bysort_prefix_val,
      by_group_vars = character(0),
      by_sort_vars = character(0),
      is_quietly_prefix = is_quietly_prefix_val,
      is_capture_prefix = is_capture_prefix_val,
      is_xi_prefix = is_xi_prefix_val
    ))
  }

  stata_cmd = get_stata_full_cmd_name(cmd_token_original)
  rest_of_cmd = if (length(parts[[1]]) > 1 && !is.na(parts[[1]][2])) stringi::stri_trim_both(parts[[1]][2]) else NA_character_

  if (stata_cmd == "bysort" || stata_cmd == "by") {
    is_by_prefix_val = FALSE
    is_bysort_prefix_val = FALSE
    by_group_vars = character(0)
    by_sort_vars = character(0)
    if (stata_cmd == "by") {
      stata_cmd = "bysort"
    }
  }

  return(list(
    stata_cmd_original = cmd_token_original,
    stata_cmd = stata_cmd,
    rest_of_cmd = rest_of_cmd,
    is_by_prefix = is_by_prefix_val,
    is_bysort_prefix = is_bysort_prefix_val,
    by_group_vars = by_group_vars,
    by_sort_vars = by_sort_vars,
    is_quietly_prefix = is_quietly_prefix_val,
    is_capture_prefix = is_capture_prefix_val,
    is_xi_prefix = is_xi_prefix_val
  ))
}

# Helper function to get macro names from a tempfile command's rest_of_cmd
get_tempfile_macros = function(rest_of_cmd_for_tempfile) {
  restore.point("get_tempfile_macros")
  if (is.na(rest_of_cmd_for_tempfile) || rest_of_cmd_for_tempfile == "") return(character(0))
  stringi::stri_split_regex(rest_of_cmd_for_tempfile, "\\s+")[[1]] %>%
    stringi::stri_trim_both() %>%
    .[. != ""]
}

# Helper function to unquote Stata string literals
unquote_stata_string_literal = function(s) {
  restore.point("unquote_stata_string_literal")
  if (is.na(s) || s == "") return(s)
  if (dplyr::coalesce(stringi::stri_startswith_fixed(s, "\"") && stringi::stri_endswith_fixed(s, "\""), FALSE)) {
    return(stringi::stri_sub(s, 2, -2))
  }
  if (dplyr::coalesce(stringi::stri_startswith_fixed(s, "'") && stringi::stri_endswith_fixed(s, "'"), FALSE)) {
    return(stringi::stri_sub(s, 2, -2))
  }
  return(s)
}

# Helper function to ensure a string is quoted for R literal use if not already
quote_for_r_literal = function(s) {
  restore.point("quote_for_r_literal")
  if (is.na(s)) return("NA_character_")
  if (length(s) == 0) return("character(0)")

  s = as.character(s[1])
  if (s == "") return("\"\"")

  return(encodeString(s, quote = "\""))
}

# Helper function to resolve Stata filenames (literal or macro) to R path expressions
resolve_stata_filename = function(raw_filename_token, cmd_df, line_num, default_base_dir_var = "working_dir") {
  restore.point("resolve_stata_filename")
  unquoted_content = unquote_stata_string_literal(raw_filename_token)

  if (dplyr::coalesce(stringi::stri_startswith_fixed(unquoted_content, "`") && stringi::stri_endswith_fixed(unquoted_content, "'"), FALSE)) {
    macro_name = stringi::stri_sub(unquoted_content, 2, -2)

    found_def_line = NA_integer_
    for (i in rev(seq_len(line_num - 1L))) {
      if (cmd_df$stata_cmd[i] == "tempfile") {
        defined_macros = get_tempfile_macros(cmd_df$rest_of_cmd[i])
        if (macro_name %in% defined_macros) {
          found_def_line = cmd_df$line[i]
          break
        }
      }
    }

    if (!is.na(found_def_line)) {
      return(paste0("R_tempfile_L", found_def_line, "_", macro_name, "_path"))
    } else {
      warning(paste0("Macro ", unquoted_content, " in command at line ", line_num, " not resolved from tempfile. Treating as literal string."))
      return(quote_for_r_literal(unquoted_content))
    }
  } else {
    is_absolute_path = dplyr::coalesce(stringi::stri_startswith_fixed(unquoted_content, "/"), FALSE) ||
      dplyr::coalesce(stringi::stri_detect_regex(unquoted_content, "^[A-Za-z]:[\\\\/]"), FALSE)

    if (is_absolute_path) {
      return(quote_for_r_literal(unquoted_content))
    } else {
      return(paste0("file.path(stata2r_env$", default_base_dir_var, ", ", quote_for_r_literal(unquoted_content), ")"))
    }
  }
}

get_xi_base_name = function(varname) {
  if (base::endsWith(varname, "_factor")) {
    return(stringi::stri_replace_last_fixed(varname, "_factor", "_f"))
  } else if (varname == "region_cat") {
    return("region_ca")
  } else {
    return(varname)
  }
}

get_xi_interaction_basename = function(var1, var2) {
  short_var1 = stringi::stri_sub(var1, 1, min(stringi::stri_length(var1), 3))
  short_var2 = stringi::stri_sub(var2, 1, min(stringi::stri_length(var2), 3))
  return(paste0(short_var1, "X", short_var2))
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/stata_cmd_utils.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/stata_expression_translator.R
```
translate_stata_expression_to_r = function(stata_expr, context = list(is_by_group = FALSE), r_value_mappings = NULL) {
  restore.point("translate_stata_expression_to_r")

  if (is.null(stata_expr) || length(stata_expr) == 0 || !is.character(stata_expr)) {
    stata_expr = NA_character_
  } else {
    stata_expr = as.character(stata_expr[1])
  }

  if (is.na(stata_expr) || stata_expr == "") {
    return("NA_real_")
  }

  r_expr = stata_expr

  # --- Handle string literals by replacing them with unique placeholders ---
  string_literal_map = list()
  placeholder_counter = 0
  literal_matches_list = stringi::stri_match_all_regex(r_expr, '"[^"]*"|\'[^\']*\'')
  if (length(literal_matches_list) > 0 && !is.null(literal_matches_list[[1]]) &&
      NROW(literal_matches_list[[1]]) > 0 && !is.na(literal_matches_list[[1]][1,1])) {
    unique_literals = unique(literal_matches_list[[1]][,1])
    for (literal_text in unique_literals) {
      placeholder_counter = placeholder_counter + 1
      placeholder = paste0("_", placeholder_counter, "STATA2R_SLIT_")
      r_expr = stringi::stri_replace_all_fixed(r_expr, literal_text, placeholder)
      string_literal_map[[placeholder]] = literal_text
    }
  }

  # --- Handle r() and e() values using placeholders first ---
  # This prevents later generic regex rewrites from corrupting mapped expressions
  # such as stata2r_env$stata_r_val_L27_mean.
  macro_placeholder_map = list()
  macro_placeholder_counter = 0
  if (!is.null(r_value_mappings) && length(r_value_mappings) > 0) {
    sorted_macro_names = names(r_value_mappings)[order(stringi::stri_length(names(r_value_mappings)), decreasing = TRUE)]
    for (stata_macro_name in sorted_macro_names) {
      macro_placeholder_counter = macro_placeholder_counter + 1
      macro_placeholder = paste0("_", macro_placeholder_counter, "STATA2R_MACRO_")
      r_expr = stringi::stri_replace_all_fixed(r_expr, stata_macro_name, macro_placeholder)
      macro_placeholder_map[[macro_placeholder]] = r_value_mappings[[stata_macro_name]]
    }
  }

  # Step 1: Handle Stata missing value literals '.', '.a', ..., '.z'
  r_expr = stringi::stri_replace_all_regex(r_expr, "(?<![0-9a-zA-Z_])\\.[a-zA-Z]?(?![0-9a-zA-Z_])", "NA_real_")

  # Step 2: Translate Stata logical operators and missing value comparisons.
  r_expr = stringi::stri_replace_all_regex(r_expr, "(\\b[a-zA-Z_][a-zA-Z0-9_.]*\\b)\\s*==\\s*NA_real_", "sfun_missing($1)")
  r_expr = stringi::stri_replace_all_regex(r_expr, "(\\b[a-zA-Z_][a-zA-Z0-9_.]*\\b)\\s*!=\\s*NA_real_", "!sfun_missing($1)")
  r_expr = stringi::stri_replace_all_regex(r_expr, "(?<![<>=!~])\\s*=\\s*(?![=])", " == ")
  r_expr = stringi::stri_replace_all_regex(r_expr, "\\s+~=\\s+", " != ")

  # Step 3: Translate Stata special variables and indexing (e.g., _n, _N, var[_n-1])
  r_expr = stringi::stri_replace_all_regex(r_expr, "(\\w+)\\[_n\\s*-\\s*(\\d+)\\]", "dplyr::lag(`$1`, n = $2)")
  r_expr = stringi::stri_replace_all_regex(r_expr, "(\\w+)\\[_n\\s*\\+\\s*(\\d+)\\]", "dplyr::lead(`$1`, n = $2)")
  r_expr = stringi::stri_replace_all_regex(r_expr, "(\\w+)\\[_n\\]", "`$1`")
  r_expr = stringi::stri_replace_all_regex(r_expr, "\\b_n\\b", "dplyr::row_number()")
  r_expr = stringi::stri_replace_all_regex(r_expr, "\\b_N\\b", "dplyr::n()")

  # Step 4: Iteratively translate Stata functions (e.g., cond(), round(), log(), etc.)
  old_r_expr = ""
  while (dplyr::coalesce(r_expr != old_r_expr, FALSE)) {
    old_r_expr = r_expr
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bcond\\(([^,]+),([^,]+),([^)]+)\\)", "sfun_stata_cond($1, $2, $3)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bround\\(([^,]+),([^)]+)\\)", "sfun_stata_round($1, $2)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bround\\(([^)]+)\\)", "sfun_stata_round($1, 1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bmod\\(([^,]+),([^)]+)\\)", "($1 %% $2)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bmissing\\(([^)]+)\\)", "sfun_missing($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\blog\\(([^)]+)\\)", "log($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bsqrt\\(([^)]+)\\)", "sqrt($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bint\\(([^)]+)\\)", "trunc($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bstrtrim\\(([^)]+)\\)", "stringi::stri_trim_right($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bstritrim\\(([^)]+)\\)", "sfun_stritrim($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\blower\\(([^)]+)\\)", "stringi::stri_trans_tolower($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bupper\\(([^)]+)\\)", "stringi::stri_trans_toupper($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bsubstr\\(([^,]+),([^,]+),([^)]+)\\)", "stringi::stri_sub($1, from = $2, length = $3)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bsubinstr\\(([^,]+),([^,]+),([^,]+),([^)]+)\\)", "sfun_subinstr($1, $2, $3, $4)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bstrpos\\(([^,]+),([^)]+)\\)", "sfun_strpos($1, $2)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\blength\\(([^)]+)\\)", "stringi::stri_length($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bstrlen\\(([^)]+)\\)", "stringi::stri_length($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bstring\\(([^)]+)\\)", "sfun_string($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bruniform\\(\\)", "stats::runif(dplyr::n())")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bdate\\(([^,]+),([^,]+),([^)]+)\\)", "sfun_stata_date($1, $2, $3)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bdate\\(([^,]+),([^)]+)\\)", "sfun_stata_date($1, $2)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bmdy\\(([^,]+),([^,]+),([^)]+)\\)", "sfun_stata_mdy($1, $2, $3)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\byear\\(([^)]+)\\)", "sfun_year($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bmonth\\(([^)]+)\\)", "sfun_month($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bday\\(([^)]+)\\)", "sfun_day($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bqofd\\(([^)]+)\\)", "sfun_qofd($1)")
    r_expr = stringi::stri_replace_all_regex(r_expr, "\\bdow\\(([^)]+)\\)", "sfun_dow($1)")
  }

  if (is.na(r_expr) || r_expr == "") {
    warning(paste0("R expression became NA or empty after function translation. Original Stata expression: '", stata_expr, "'"))
    return("NA_real_")
  }

  # Step 5: Quote bare variable names with backticks
  r_reserved_words = c(
    "TRUE", "FALSE", "NA_real_", "NA_character_", "NA_integer_", "NA", "NULL",
    "if_else", "coalesce", "row_number", "n", "lag", "lead", "select", "filter",
    "mutate", "group_by", "ungroup", "syms", "all_of", "everything", "matches",
    "pivot_wider", "pivot_longer", "read_dta", "write_dta", "labelled", "zap_labels",
    "zap_formats", "zap_missing", "as_factor", "parse_number",
    "mean", "sum", "median", "sd", "min", "max", "log", "sqrt", "trunc", "rank",
    "rowSums", "rowMeans", "setNames", "match", "tempfile", "file.path",
    "fmean", "fsum", "fN", "ffirst", "flast", "fmin", "fmax", "fmedian", "fsd",
    "fquantile", "fgroup_by", "fungroup", "fsubset", "frename", "bind_rows", "rep",
    "as_tibble", "inherits", "format", "as.Date", "as.numeric", "as.character", "as.integer",
    "sign", "floor", "abs", "pmax", "stringi", "base", "stats", "dplyr", "collapse", "haven",
    "readr", "tidyr", "labelled", "restorepoint", "stata2r_env",
    "sfun_missing", "sfun_stata_add", "sfun_stata_round", "sfun_string", "sfun_stritrim",
    "sfun_strpos", "sfun_subinstr", "sfun_stata_mdy", "sfun_stata_date", "sfun_day",
    "sfun_month", "sfun_qofd", "sfun_dow", "sfun_normalize_string_nas", "sfun_strip_stata_attributes",
    "sfun_compress_col_type", "sfun_is_stata_expression_string_typed", "as.logical",
    "sfun_stata_cond", "sfun_year", "sfun_stata_date_single", "e", "sfun_flag", "sfun_fdiff",
    "NROW", "length", "unique", "sapply", "vapply", "c", "list", "intersect", "setdiff",
    "warning", "stop", "paste0", "grepl", "as.logical", "ifelse", "exists", "rm",
    "is.null", "lapply", "is.na", "is.character", "is.numeric", "is.logical", "is.factor",
    "attributes", "attr", "names", "order", "unname", "duplicated", "trimws",
    "suppressWarnings", "as.data.frame", "rownames", "colnames", "head", "tail",
    "matrix", "data.frame", "vector", "character", "numeric", "integer", "logical",
    "factor", "double", "`_n`", "`_N`",
    "cur_group_id", "cur_data_all", "replace", "TRUE", "FALSE"
  )

  locations_list = stringi::stri_locate_all_regex(r_expr, "\\b([a-zA-Z_][a-zA-Z0-9_.]*)\\b")
  locations = locations_list[[1]]

  if (!is.null(locations) && NROW(locations) > 0 && !is.na(locations[1,1])) {
    locations = locations[order(locations[,2], decreasing = TRUE), , drop = FALSE]
    for (k in seq_len(NROW(locations))) {
      start_pos = locations[k,1]
      end_pos = locations[k,2]
      current_word = stringi::stri_sub(r_expr, start_pos, end_pos)

      if (current_word %in% names(string_literal_map)) {
        next
      }
      if (current_word %in% names(macro_placeholder_map)) {
        next
      }

      is_reserved = dplyr::coalesce(current_word %in% r_reserved_words, FALSE)
      is_numeric_literal = dplyr::coalesce(suppressWarnings(!is.na(as.numeric(current_word))), FALSE)

      is_already_backticked = FALSE
      if (dplyr::coalesce(start_pos > 1 && end_pos < stringi::stri_length(r_expr), FALSE)) {
        char_before = dplyr::coalesce(stringi::stri_sub(r_expr, start_pos - 1, start_pos - 1), "")
        char_after = dplyr::coalesce(stringi::stri_sub(r_expr, end_pos + 1, end_pos + 1), "")
        is_already_backticked = (char_before == "`" && char_after == "`")
      }

      if (isTRUE(!is_reserved) && isTRUE(!is_numeric_literal) && isTRUE(!is_already_backticked)) {
        r_expr = paste0(
          stringi::stri_sub(r_expr, 1, start_pos - 1),
          "`", current_word, "`",
          stringi::stri_sub(r_expr, end_pos + 1, stringi::stri_length(r_expr))
        )
      }
    }
  }

  # Step 6: Translate Stata '+' operator to sfun_stata_add for polymorphic behavior
  operand_pattern = "(?:\"[^\"]*\"|'[^']*'|\\d+(?:\\.\\d+)?(?:e[+-]?\\d+)?|\\b(?:NA_real_|NULL)\\b|\\b(?:TRUE|FALSE)\\b|`[^`]+`|\\b[a-zA-Z_][a-zA-Z0-9_.]*\\s*\\(.*?\\)\\s*|_[0-9]+STATA2R_SLIT_|_[0-9]+STATA2R_MACRO_)"
  old_r_expr_add = ""
  while (dplyr::coalesce(r_expr != old_r_expr_add, FALSE)) {
    old_r_expr_add = r_expr
    add_regex_middle_part = "\\s*(?<![<>=!~])\\+\\s*(?!\\s*\\+|\\s*=\\s*)"
    add_regex_full = paste0("(", operand_pattern, ")", add_regex_middle_part, "(", operand_pattern, ")")
    r_expr = stringi::stri_replace_all_regex(r_expr, add_regex_full, "sfun_stata_add($1, $2)")
  }

  # --- Restore mapped macro expressions from placeholders ---
  if (length(macro_placeholder_map) > 0) {
    sorted_macro_placeholders = names(macro_placeholder_map)[order(stringi::stri_length(names(macro_placeholder_map)), names(macro_placeholder_map), decreasing = TRUE)]
    for (macro_placeholder in sorted_macro_placeholders) {
      r_expr = stringi::stri_replace_all_fixed(r_expr, macro_placeholder, macro_placeholder_map[[macro_placeholder]])
    }
  }

  # --- Restore string literals from placeholders ---
  if (length(string_literal_map) > 0) {
    sorted_placeholders = names(string_literal_map)[order(stringi::stri_length(names(string_literal_map)), names(string_literal_map), decreasing = TRUE)]
    for (placeholder in sorted_placeholders) {
      r_expr = stringi::stri_replace_all_fixed(r_expr, placeholder, string_literal_map[[placeholder]])
    }
  }

  return(r_expr)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/stata_expression_translator.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/stata_na_handling.R
```
# FILE: R/stata_na.R

#' Helper to transform NA to Stata's encoding for conditions
#' In Stata, numeric missing (.) is treated as positive infinity.
to_stata_na = function(x) {
  if (is.numeric(x) || inherits(x, "Date")) {
    # Coerce to plain double to avoid strict integer/labelled casting issues with Inf
    x = as.numeric(x)
    x[is.na(x)] = Inf
  } else if (is.character(x)) {
    x[is.na(x)] = ""
  }
  x
}

#' Initialize an evaluation list with Stata NA rules
#' @param data The dataframe to base the evaluation list on
#' @return A list ready for `eval()` containing data and Stata NA mappings
s2r_setup_eval_list = function(data) {
  # 1. Apply to_stata_na to all columns
  eval_list = lapply(data, to_stata_na)

  # 2. Inject NA values as Inf to correctly evaluate comparisons (like id >= .)
  eval_list[["NA_real_"]] = Inf
  eval_list[["NA_integer_"]] = Inf
  eval_list[["NA_character_"]] = ""
  eval_list[["NA"]] = Inf

  # 3. Override sfun_missing to handle Inf as missing for evaluations
  eval_list[["sfun_missing"]] = function(x) {
    if (is.numeric(x)) {
      return(is.na(x) | is.infinite(x))
    } else if (is.character(x)) {
      return(is.na(x) | stringi::stri_trim_both(x) == "")
    }
    return(is.na(x))
  }

  return(eval_list)
}

#' List of reserved words injected by s2r_setup_eval_list
s2r_eval_reserved_words = function() {
  c("NA_real_", "NA_integer_", "NA_character_", "NA", "sfun_missing")
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/stata_na_handling.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/stata_xi.R
```
# FILE: R/stata_xi.R

#' Helper to generate xi base name
get_xi_base_name = function(varname) {
  if (base::endsWith(varname, "_factor")) {
    return(stringi::stri_replace_last_fixed(varname, "_factor", "_f"))
  } else if (varname == "region_cat") {
    return("region_ca")
  }
  return(varname)
}

#' Helper to generate xi interaction base name
get_xi_interaction_basename = function(var1, var2) {
  short_var1 = stringi::stri_sub(var1, 1, min(stringi::stri_length(var1), 3))
  short_var2 = stringi::stri_sub(var2, 1, min(stringi::stri_length(var2), 3))
  return(paste0(short_var1, "X", short_var2))
}

#' Generate dummy variables for a single categorical variable
sfun_xi_create_dummies = function(data, varname) {
  col = haven::zap_labels(data[[varname]])
  u_vals = sort(unique(col[!is.na(col)]))

  if (length(u_vals) > 0) {
    base_level = u_vals[1]
    levels_to_dummy = setdiff(u_vals, base_level)

    for (lvl in levels_to_dummy) {
      new_col = paste0("_I", get_xi_base_name(varname), "_", lvl)
      data[[new_col]] = dplyr::if_else(!is.na(col) & col == lvl, 1L, dplyr::if_else(!is.na(col) & col != lvl, 0L, NA_integer_))
      attr(data[[new_col]], "label") = paste0(varname, "==", lvl)
    }
  }
  return(data)
}

#' Runtime execution for Stata xi command
scmd_xi = function(data, var1, var2 = NA_character_) {
  restore.point("scmd_xi")

  data = sfun_xi_create_dummies(data, var1)

  if (!is.na(var2)) {
    data = sfun_xi_create_dummies(data, var2)

    col1 = haven::zap_labels(data[[var1]])
    col2 = haven::zap_labels(data[[var2]])

    u_vals1 = sort(unique(col1[!is.na(col1)]))
    u_vals2 = sort(unique(col2[!is.na(col2)]))

    if (length(u_vals1) > 0 && length(u_vals2) > 0) {
      levels1 = setdiff(u_vals1, u_vals1[1])
      levels2 = setdiff(u_vals2, u_vals2[1])

      base = get_xi_interaction_basename(var1, var2)

      for (lvl1 in levels1) {
        for (lvl2 in levels2) {
          new_col = paste0("_I", base, "_", lvl1, "_", lvl2)
          is_match = !is.na(col1) & !is.na(col2) & col1 == lvl1 & col2 == lvl2
          is_valid_non_match = !is.na(col1) & !is.na(col2) & (col1 != lvl1 | col2 != lvl2)

          data[[new_col]] = dplyr::if_else(is_match, 1L, dplyr::if_else(is_valid_non_match, 0L, NA_integer_))
          attr(data[[new_col]], "label") = paste0(var1, "==", lvl1, " & ", var2, "==", lvl2)
        }
      }
    }
  }

  return(data)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/stata_xi.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/translate_stata_expression_with_r_values.R
```
translate_stata_expression_with_r_values = function(stata_expr, line_num, cmd_df, context) {
  restore.point("translate_stata_expression_with_r_values")

  r_value_mappings = list()

  # --- Handle r() values from summarize/tabulate ---
  # Find the most recent summarize/tabulate command before the current line that was translated
  most_recent_r_producer_line_idx = NA_integer_
  for (i in rev(seq_len(line_num - 1L))) {
    if (cmd_df$stata_cmd[i] %in% c("summarize", "su", "tabulate", "tab") && cmd_df$do_translate[i]) {
      most_recent_r_producer_line_idx = i
      break
    }
  }

  if (!is.na(most_recent_r_producer_line_idx)) {
    prev_cmd_obj = cmd_df[most_recent_r_producer_line_idx, ]
    line_prefix_r = paste0("stata_r_val_L", prev_cmd_obj$line, "_")

    # Populate r_value_mappings based on stored runtime values in stata2r_env
    r_value_mappings[["r(N)"]] = paste0("stata2r_env$", line_prefix_r, "N")
    r_value_mappings[["r(mean)"]] = paste0("stata2r_env$", line_prefix_r, "mean")
    r_value_mappings[["r(sd)"]] = paste0("stata2r_env$", line_prefix_r, "sd")
    r_value_mappings[["r(min)"]] = paste0("stata2r_env$", line_prefix_r, "min")
    r_value_mappings[["r(max)"]] = paste0("stata2r_env$", line_prefix_r, "max")
    r_value_mappings[["r(sum)"]] = paste0("stata2r_env$", line_prefix_r, "sum")
    r_value_mappings[["r(p50)"]] = paste0("stata2r_env$", line_prefix_r, "p50")
  }

  # --- Handle e() values from estimation commands ---
  most_recent_e_producer_line_idx = NA_integer_
  for (i in rev(seq_len(line_num - 1L))) {
    if (cmd_df$stata_cmd[i] %in% stata_estimation_cmds && cmd_df$do_translate[i]) {
      most_recent_e_producer_line_idx = i
      break
    }
  }

  if (!is.na(most_recent_e_producer_line_idx)) {
    prev_cmd_obj_e = cmd_df[most_recent_e_producer_line_idx, ]
    line_prefix_e_base = paste0("stata_e_L", prev_cmd_obj_e$line, "_")

    if ("e(sample)" %in% unlist(prev_cmd_obj_e$e_results_needed)) {
      r_value_mappings[["e(sample)"]] = paste0("stata2r_env$stata_e_sample_L", prev_cmd_obj_e$line)
    }
    if ("e(N)" %in% unlist(prev_cmd_obj_e$e_results_needed)) {
      r_value_mappings[["e(N)"]] = paste0("stata2r_env$", line_prefix_e_base, "N")
    }
    if ("e(r2)" %in% unlist(prev_cmd_obj_e$e_results_needed)) {
      r_value_mappings[["e(r2)"]] = paste0("stata2r_env$", line_prefix_e_base, "r2")
    }
    if ("e(df_r)" %in% unlist(prev_cmd_obj_e$e_results_needed)) {
      r_value_mappings[["e(df_r)"]] = paste0("stata2r_env$", line_prefix_e_base, "df_r")
    }
    if ("e(rmse)" %in% unlist(prev_cmd_obj_e$e_results_needed)) {
      r_value_mappings[["e(rmse)"]] = paste0("stata2r_env$", line_prefix_e_base, "rmse")
    }
  }

  translated_expr = translate_stata_expression_to_r(
    stata_expr,
    context = context,
    r_value_mappings = r_value_mappings
  )
  return(translated_expr)
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/translate_stata_expression_with_r_values.R

-----------------------------------------------------------


# FILE: /home/rstudio/aicoder/stata2r/R/varlist.R
```
# Runtime helper functions for Stata variable list expansion

#' Expand Stata patterns (*, -, abbreviations) into actual column names at runtime
#' @param varlist_str Character string of the Stata varlist
#' @param data_cols Character vector of available columns in the dataset
expand_varlist = function(varlist_str, data_cols) {
  if (is.na(varlist_str) || trimws(varlist_str) == "") return(character(0))

  # Tokenize by whitespace
  tokens = stringi::stri_split_regex(trimws(varlist_str), "\\s+")[[1]]
  tokens = tokens[tokens != ""]

  expanded_vars = character(0)

  for (tok in tokens) {
    if (grepl("-", tok, fixed = TRUE)) {
      # Range: var1-var5
      parts = strsplit(tok, "-", fixed = TRUE)[[1]]
      if (length(parts) == 2 && all(parts %in% data_cols)) {
        idx1 = match(parts[1], data_cols)
        idx2 = match(parts[2], data_cols)
        # Ensure order is correct regardless of dataset column order
        range_idx = if (idx1 <= idx2) idx1:idx2 else idx1:idx2
        expanded_vars = c(expanded_vars, data_cols[range_idx])
      } else {
        expanded_vars = c(expanded_vars, tok) # fallback, might error later
      }
    } else if (grepl("\\*|\\?", tok)) {
      # Wildcards: var* or v?r
      rx = glob2rx(tok)
      matches = data_cols[grepl(rx, data_cols)]
      expanded_vars = c(expanded_vars, matches)
    } else {
      # Exact match or abbreviation
      if (tok %in% data_cols) {
        expanded_vars = c(expanded_vars, tok)
      } else {
        # Try abbreviation
        mcols = data_cols[startsWith(data_cols, tok)]
        if (length(mcols) == 1) {
          expanded_vars = c(expanded_vars, mcols[1])
        } else if (length(mcols) > 1) {
          # Matches multiple (ambiguous in strict Stata, but we take first or all depending on rules)
          # Stata errors on ambiguous abbreviation. We take the first for safety or error.
          expanded_vars = c(expanded_vars, mcols[1])
        } else {
          expanded_vars = c(expanded_vars, tok) # leave as is
        }
      }
    }
  }

  return(unique(expanded_vars))
}
```
# END OF FILE: /home/rstudio/aicoder/stata2r/R/varlist.R

-----------------------------------------------------------




##################################
# Your Task
##################################

I am currently profiling the code. Look at:


find_data_run_path = function(pid_row, srun_df, pid=NULL) {
  restore.point("find_data_run_path")

  # All runid in same load block until pid
  path = which(srun_df$load_block == srun_df$load_block[pid_row] & srun_df$.ROW <= pid_row)

  # If we start with a restore command then jump to previous preserve
  # and then add all rows with the same load_block
  while (TRUE) {
    if (srun_df$cmd[path[1]] == "restore") {
      pr_row = srun_df$preserve_row[path[1]]
      new_path = which(srun_df$load_block == srun_df$load_block[pr_row] & srun_df$.ROW < pr_row)
      path = c(new_path, path[-1])
      next
    }
    break
  }

  # Adapt path: Use stata2r to accurately determine which commands have data
  # manipulation side effects or are relied upon by later commands.
  stata_code = srun_df$cmdline[path]
  stata_code = gsub("\n", " ", stata_code, fixed = TRUE)
  cmd_df = stata2r::s2r_check_mod(stata_code)

  cmd_types = drf_stata_cmd_types()
  allow = c(cmd_types$scalar, cmd_types$xtset)

  keep = seq_along(path) %in% c(1, length(path)) |
    cmd_df$is_mod |
    srun_df$cmd[path] %in% allow |
    srun_df$runid[path] %in% pid

  path = path[keep]

  return( tibble(pid=srun_df$runid[pid_row], runid=srun_df$runid[path]))
}

Do I really need the stata2r::s2r_check_mod(stata_code) calls for every path I generate? I guess later (or earlier) I also make such calls only once for all potential commands that actually modify once on run_df... Could this be sped up? 

But it is also not straightforward, e.g.  initially make a fast guess of potential modifying commands later check once which from the set of potential mod commands on all paths actually modify? Does this make sense. Think about implementation.  
